/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AGRAV } from "./AGRAV";
export type { AISO } from "./AISO";
export type { GREEN } from "./GREEN";
export type { LOVE } from "./LOVE";
export type { RECYCLE } from "./RECYCLE";
export type { UKID } from "./UKID";
export type { YANAI } from "./YANAI";
