/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DeadManSwitchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateStateB"
      | "certificateHash"
      | "confirmedAt"
      | "gnosisSafe"
      | "missionTreasury"
      | "stateBActive"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StateBActivated"): EventFragment;

  encodeFunctionData(
    functionFragment: "activateStateB",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificateHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmedAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisSafe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "missionTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateBActive",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "activateStateB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificateHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gnosisSafe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "missionTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateBActive",
    data: BytesLike
  ): Result;
}

export namespace StateBActivatedEvent {
  export type InputTuple = [
    certificateHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [certificateHash: string, timestamp: bigint];
  export interface OutputObject {
    certificateHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeadManSwitch extends BaseContract {
  connect(runner?: ContractRunner | null): DeadManSwitch;
  waitForDeployment(): Promise<this>;

  interface: DeadManSwitchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateStateB: TypedContractMethod<
    [_certificateHash: BytesLike],
    [void],
    "nonpayable"
  >;

  certificateHash: TypedContractMethod<[], [string], "view">;

  confirmedAt: TypedContractMethod<[], [bigint], "view">;

  gnosisSafe: TypedContractMethod<[], [string], "view">;

  missionTreasury: TypedContractMethod<[], [string], "view">;

  stateBActive: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateStateB"
  ): TypedContractMethod<[_certificateHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "certificateHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confirmedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gnosisSafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "missionTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stateBActive"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "StateBActivated"
  ): TypedContractEvent<
    StateBActivatedEvent.InputTuple,
    StateBActivatedEvent.OutputTuple,
    StateBActivatedEvent.OutputObject
  >;

  filters: {
    "StateBActivated(bytes32,uint256)": TypedContractEvent<
      StateBActivatedEvent.InputTuple,
      StateBActivatedEvent.OutputTuple,
      StateBActivatedEvent.OutputObject
    >;
    StateBActivated: TypedContractEvent<
      StateBActivatedEvent.InputTuple,
      StateBActivatedEvent.OutputTuple,
      StateBActivatedEvent.OutputObject
    >;
  };
}
