#!/bin/bash
# Create 100 Paperclip tasks for Antigravity project
COMPANY_ID="f8d20b4a-4242-4b2f-b6bd-b763b7012af0"
PROJECT_ID="70291e41-a61b-4463-8b32-fc0ec1a8ea32"
BASE="paperclipai issue create --company-id $COMPANY_ID --project-id $PROJECT_ID"

create_task() {
  local num="$1"
  local title="$2"
  local desc="$3"
  local priority="$4"
  shift 4
  # skip if already exists by title check
  $BASE --title "$title" --description "$desc" --priority "$priority" --status backlog 2>&1
  echo "[$num] Created: $title"
}

# FRONTEND FIXES (1-20)
create_task 1 "Fix MissionControlDashboard TypeScript errors" "Resolve type errors in apps/mission-control/src/components/MissionControlDashboard.tsx. Check for missing prop types, interface definitions, and any unused imports." "high"
create_task 2 "Add loading skeletons to mission-control dashboard" "Replace spinners with skeleton loading states for all data-fetching components in the mission-control dashboard for better perceived performance." "medium"
create_task 3 "Fix responsive layout on mission-control mobile view" "Dashboard elements overflow on mobile. Review CSS grid/flex layouts and ensure proper breakpoints at 768px and 480px." "medium"
create_task 4 "Implement error boundaries in React components" "Add error boundary components to prevent full app crashes when individual components throw. Include fallback UI with retry options." "high"
create_task 5 "Fix broken image links in marketing-assets" "Audit all image paths in marketing-assets and ensure they resolve correctly. Check for case-sensitivity issues on Linux vs Windows." "low"
create_task 6 "Add keyboard navigation to dashboard" "Ensure all interactive elements in MissionControlDashboard are keyboard accessible. Implement proper tab order, focus indicators, and ARIA labels." "medium"
create_task 7 "Fix CORS issues in mission-control-api dev mode" "API calls from frontend to backend fail with CORS errors in development. Configure cors middleware to allow localhost origins." "high"
create_task 8 "Implement dark/light theme toggle" "Add theme switcher to the app header. Persist user preference in localStorage. Ensure all components respect the active theme variable." "low"
create_task 9 "Fix date/time display timezone inconsistencies" "Timestamps shown in mixed timezones across dashboard. Standardize to UTC and convert to local time in the UI layer." "medium"
create_task 10 "Add input validation to all form components" "Forms lack client-side validation. Add required field indicators, inline error messages, and prevent submission of invalid data." "medium"
create_task 11 "Fix memory leak in WebSocket subscriptions" "WebSocket connections in mission-control are not properly cleaned up on component unmount, causing memory leaks over time." "high"
create_task 12 "Implement real-time data refresh indicator" "Show a subtle indicator when dashboard data is being refreshed from the API. Prevent double-refresh on rapid user interactions." "low"
create_task 13 "Fix pagination in ops-runs log viewer" "The ops-runs.jsonl viewer in mission-control-api has broken pagination. Implement proper offset/limit pagination." "medium"
create_task 14 "Add search/filter to mission-control dashboard widgets" "Implement client-side filtering for dashboard tables and lists. Support text search, date range, and status filters." "medium"
create_task 15 "Fix broken SVG icon rendering" "Several icons render as broken images in the UI. Audit all SVG imports and ensure they reference valid assets in the bundle." "low"
create_task 16 "Implement bulk actions for task tables" "Add checkbox multi-select and bulk action toolbar (archive, delete, assign) to task/ops tables in mission-control." "low"
create_task 17 "Fix dropdown menus closing on accidental hover" "Context menus and dropdowns close when mouse briefly exits. Add a small delay before closing to prevent accidental dismissal." "low"
create_task 18 "Add confirmation dialogs for destructive actions" "Delete/Archive operations lack confirmation. Implement modal dialogs for all destructive actions with explicit user confirmation." "medium"
create_task 19 "Fix z-index stacking context issues" "Modal dialogs appear behind other elements in certain browser/OS combinations. Audit and fix z-index values across all overlay components." "low"
create_task 20 "Implement toast notifications for async operations" "Replace console.log error handling with user-facing toast notifications for save, delete, and API operations." "medium"

# API IMPROVEMENTS (21-40)
create_task 21 "Add request deduplication to mission-control-api" "Multiple simultaneous identical requests cause redundant API calls. Implement request deduplication using a Map of pending promises." "high"
create_task 22 "Implement proper error response format" "API returns inconsistent error shapes. Standardize all error responses to {code, message, details} format with appropriate HTTP status codes." "medium"
create_task 23 "Add request validation middleware" "Raw requests bypass validation. Implement Joi/Zod validation middleware on all POST/PUT endpoints to reject malformed requests early." "high"
create_task 24 "Implement API rate limiting" "No rate limiting on public endpoints. Add per-IP and per-token rate limiting using a sliding window algorithm (e.g. 100 req/min)." "high"
create_task 25 "Add pagination to list endpoints" "All list endpoints return unbounded results. Implement cursor-based pagination with page_size, cursor, and has_more fields." "medium"
create_task 26 "Add API versioning strategy" "No API versioning. Implement /v1/ prefix on all routes and document breaking vs non-breaking change policy." "medium"
create_task 27 "Implement WebSocket authentication" "WebSocket endpoints lack authentication. Validate JWT tokens on connection and reject unauthorized clients." "high"
create_task 28 "Add structured logging to API" "Console.log used throughout. Replace with structured logger (pino/winston) that outputs JSON with request_id, user_id, and duration fields." "medium"
create_task 29 "Implement webhook retry logic" "Failed webhooks are silently dropped. Implement exponential backoff retry queue with dead-letter handling after max retries." "medium"
create_task 30 "Add API health check endpoint" "No dedicated health endpoint. Add /health that checks DB, cache, and external service connectivity with detailed status." "medium"
create_task 31 "Implement input sanitization" "User inputs are not sanitized before DB insertion. Add sanitization layer to prevent XSS and injection attacks." "high"
create_task 32 "Add OpenAPI/Swagger documentation" "API lacks interactive documentation. Generate OpenAPI 3.0 spec and serve Swagger UI at /docs for all endpoints." "medium"
create_task 33 "Implement partial update (PATCH) semantics" "All updates do full replaces. Implement proper PATCH semantics that merge changes without overwriting omitted fields." "medium"
create_task 34 "Add API response caching headers" "No cache headers on GET responses. Add ETag/Last-Modified and Cache-Control headers appropriate to each endpoint's volatility." "low"
create_task 35 "Implement cursor-based pagination for ops-runs" "ops-runs.jsonl grows unbounded. Implement cursor pagination to allow efficient traversal without loading entire file." "medium"
create_task 36 "Add database query timeout handling" "Slow queries hang indefinitely. Add query timeout configuration and return 504 Gateway Timeout after threshold." "medium"
create_task 37 "Implement graceful shutdown for API server" "SIGTERM causes abrupt connection drops. Implement graceful shutdown that drains active requests before exiting." "medium"
create_task 38 "Add JWT refresh token rotation" "Tokens never expire or rotate. Implement refresh token rotation with sliding window expiration and revocation list." "high"
create_task 39 "Add API request tracing (correlation IDs)" "Hard to trace requests across services. Add X-Request-ID header propagation through all services and log it on every span." "medium"
create_task 40 "Implement API idempotency keys" "Retry-safe operations (payments, status changes) lack idempotency keys. Support Idempotency-Key header to prevent duplicate operations." "high"

# DEPLOYMENT (41-55)
create_task 41 "Set up CI/CD pipeline for Antigravity" "No automated deployment pipeline. Set up GitHub Actions to run tests, lint, and deploy on merge to main." "high"
create_task 42 "Configure production environment variables" "Prod env vars are hardcoded or missing. Document all required env vars, set up .env.production, and use a secrets manager." "high"
create_task 43 "Set up staging environment" "Only production exists. Create a staging environment that mirrors prod for QA and integration testing before releases." "medium"
create_task 44 "Implement blue-green deployment" "Deployments cause downtime. Set up blue-green deployment strategy with zero-downtime switching between old and new versions." "medium"
create_task 45 "Add Docker container health checks" "Containers run without health probes. Add HEALTHCHECK directives to Dockerfiles and configure container orchestrator probes." "medium"
create_task 46 "Set up log aggregation for production" "Logs are only visible via docker compose logs. Configure log aggregation (ELK/Graylog/Datadog) for centralized log viewing." "medium"
create_task 47 "Implement database migration strategy" "No versioned migrations. Set up Flyway or Liquibase for reproducible schema changes across environments." "high"
create_task 48 "Add deployment rollback procedure" "No rollback plan exists. Document and automate rollback procedure that redeploys the previous known-good image/tag." "medium"
create_task 49 "Configure CDN for static assets" "Static assets served from app server. Offload to CDN (Cloudflare/R2) with appropriate cache headers and asset fingerprinting." "low"
create_task 50 "Set up monitoring and alerting" "No production monitoring. Configure Prometheus metrics, Grafana dashboards, and PagerDuty alerts for key SLOs (availability, latency)." "high"
create_task 51 "Implement feature flags" "Code changes require full deploys. Integrate a feature flag system to enable/disable features without redeployment." "medium"
create_task 52 "Add deployment pre-flight checks" "Deploys proceed even when checks fail. Add pre-flight checks: DB connectivity, disk space, dependency availability before deploying." "medium"
create_task 53 "Configure auto-scaling rules" "No auto-scaling. Define CPU/memory scaling triggers for production workloads with min/max instance counts." "medium"
create_task 54 "Set up secrets rotation procedure" "Secrets never rotate. Implement automated rotation for API keys, DB passwords, and JWT signing keys with zero downtime." "high"
create_task 55 "Add deployment canary analysis" "Full rollouts carry risk. Implement canary deployments that route small % of traffic to new version before full promotion." "medium"

# TESTING (56-70)
create_task 56 "Set up unit test framework" "No unit tests exist. Configure Jest/Vitest with coverage reporting. Target 80% coverage for business logic modules." "high"
create_task 57 "Add integration tests for API endpoints" "API endpoints lack integration tests. Write tests using Supertest that hit real DB and verify request/response contracts." "high"
create_task 58 "Implement E2E test suite" "No end-to-end tests. Set up Playwright or Cypress to test critical user flows: signup, login, dashboard load, and core actions." "high"
create_task 59 "Add test coverage reporting" "Coverage is not tracked. Integrate coverage reporting to CI, fail builds below threshold, and track coverage over time." "medium"
create_task 60 "Write tests for WebSocket handlers" "WebSocket message handlers have no tests. Write unit tests that verify message parsing, validation, and response formatting." "medium"
create_task 61 "Add snapshot tests for UI components" "UI regression undetected. Add snapshot tests (Jest/Vitest) for key components to catch unintended visual changes." "low"
create_task 62 "Implement contract testing for API" "Frontend/backend can drift apart. Implement Pact contract tests to verify API responses match frontend expectations." "medium"
create_task 63 "Add performance benchmarks" "No performance regression detection. Add benchmark tests that fail if key API endpoints exceed latency SLOs under load." "medium"
create_task 64 "Write tests for auth middleware" "Auth logic lacks test coverage. Write unit tests covering JWT validation, token expiry, refresh flows, and revocation." "high"
create_task 65 "Add chaos engineering tests" "No resilience testing. Implement chaos tests (kill process, inject latency, fill disk) to verify graceful degradation." "medium"
create_task 66 "Implement test data factories" "Tests create data ad-hoc. Build factory functions that create consistent, realistic test data for all entities." "medium"
create_task 67 "Add mutation testing" "Tests pass vacuously. Run mutation testing (Stryker) to verify tests actually catch code bugs, not just pass trivially." "low"
create_task 68 "Write tests for data processing scripts" "Data transformation scripts have no tests. Add unit tests for generate_all_assets.py and other data processing scripts." "low"
create_task 69 "Add test environment isolation" "Tests hit shared dev DB. Configure per-test DB using transactions or in-memory DB to prevent test pollution." "medium"
create_task 70 "Implement property-based testing" "Edge cases missed by example-based tests. Add fast-check property tests for data serialization, parsing, and transformations." "low"

# DOCS (71-80)
create_task 71 "Write README.md for mission-control" "No README for the mission-control app. Document setup, local development, key features, and architecture decisions." "medium"
create_task 72 "Document API endpoint specifications" "API has no documentation. Write OpenAPI specs and usage examples for all endpoints, including request/response schemas." "high"
create_task 73 "Add architecture decision records (ADRs)" "Key decisions are not recorded. Write ADRs for: auth strategy, data storage approach, deployment topology, and API design choices." "low"
create_task 74 "Document onboarding runbook" "New contributors lack guidance. Write a step-by-step onboarding doc covering repo clone, env setup, first run, and common issues." "medium"
create_task 75 "Create ops runbook for production incidents" "No incident response playbooks. Document escalation procedures, common failure modes, and recovery steps for production issues." "high"
create_task 76 "Document deployment procedure" "Deploy steps are tribal knowledge. Write detailed deployment runbook covering pre-checks, execution, post-deploy verification, and rollback." "medium"
create_task 77 "Add inline code documentation" "Critical modules lack JSDoc/comments. Add comprehensive inline docs to complex business logic, data transformations, and auth flows." "low"
create_task 78 "Create data dictionary for ops-runs schema" "ops-runs.jsonl schema is undocumented. Define all fields, types, and meanings in a data dictionary with examples." "low"
create_task 79 "Document marketing-assets structure" "Unclear what assets are for. Add README explaining the directory structure, naming conventions, and usage guidelines for assets." "low"
create_task 80 "Write contributing guidelines" "No contribution guide. Document branch strategy, commit message format, PR process, code review expectations, and coding standards." "medium"

# SECURITY (81-90)
create_task 81 "Conduct dependency audit" "No known vulnerabilities assessment. Run npm audit / pip audit and Snyk/Dependabot to identify and fix vulnerable dependencies." "high"
create_task 82 "Implement SQL injection prevention review" "All DB queries reviewed for injection risk. Use parameterized queries exclusively, audit raw SQL, and add automated tests." "high"
create_task 83 "Add CSP headers to API responses" "No Content-Security-Policy headers. Implement strict CSP headers to mitigate XSS and data injection attacks." "high"
create_task 84 "Implement CSRF protection" "State-changing API calls lack CSRF tokens. Implement double-submit cookie pattern or SameSite cookie policy." "high"
create_task 85 "Rotate all secrets and keys" "Production secrets may be compromised or old. Rotate all API keys, JWT secrets, DB passwords, and external service credentials." "high"
create_task 86 "Add input allowlist validation" "Inputs only reject obvious bad values. Implement strict allowlists for all user inputs (regex, enum, type validation)." "high"
create_task 87 "Implement request size limits" "No payload size limits. Add limits on request body size and nested object depth to prevent DoS via large payloads." "medium"
create_task 88 "Add security headers (HSTS, X-Frame-Options, etc.)" "Missing security headers. Add Strict-Transport-Security, X-Content-Type-Options, X-Frame-Options, Referrer-Policy." "medium"
create_task 89 "Audit third-party scripts and dependencies" "Third-party scripts not reviewed. Audit all CDN scripts, tracking pixels, and analytics for supply chain risks." "medium"
create_task 90 "Implement secure file upload handling" "File uploads lack validation. Enforce type allowlists, size limits, virus scanning, and store uploads outside webroot." "high"

# PERFORMANCE (91-100)
create_task 91 "Profile and optimize mission-control dashboard load" "Dashboard is slow on first load. Profile with WebPageTest, identify render-blocking resources, and implement code splitting." "high"
create_task 92 "Add database query optimization" "Slow queries on list endpoints. Analyze query plans, add indexes on filter/sort columns, and implement query result caching." "high"
create_task 93 "Implement Redis caching layer" "No caching. Add Redis for API response caching, session storage, and rate limit counters with appropriate TTLs." "medium"
create_task 94 "Optimize marketing-assets image delivery" "Images are uncompressed and oversized. Implement WebP/AVIF conversion, lazy loading, and responsive srcset attributes." "medium"
create_task 95 "Add bundle analysis and code splitting" "Bundle size not tracked. Add webpack/vite bundle analyzer, implement route-based code splitting, and tree-shake unused code." "medium"
create_task 96 "Implement database connection pooling" "DB connections opened per request. Configure connection pool with appropriate min/max size to reduce connection overhead." "medium"
create_task 97 "Add API response compression" "Responses not compressed. Enable gzip/brotli compression for JSON responses above 1KB threshold." "low"
create_task 98 "Optimize ops-runs.jsonl read performance" "Large JSONL file read linearly. Implement line indexing, buffered reads, and consider SQLite migration for queries." "medium"
create_task 99 "Add Core Web Vitals tracking" "No user-facing performance metrics. Integrate RUM for CWV (LCP, FID, CLS) and set performance budgets in CI." "medium"
create_task 100 "Implement lazy loading for heavy components" "All components load upfront. Implement React.lazy and intersection observer for below-fold components and heavy widgets." "medium"

echo "=== All 100 tasks created ==="
