"""add_volunteer_category_and_hours

Revision ID: 12983f2b61f2
Revises: 4b5082b1640d
Create Date: 2026-03-05 00:35:50.750674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12983f2b61f2'
down_revision: Union[str, None] = '4b5082b1640d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_opportunities', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('volunteer_opportunities', sa.Column('hours_estimate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_opportunities', 'hours_estimate')
    op.drop_column('volunteer_opportunities', 'category')
    # ### end Alembic commands ###
