/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface Router100Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "_SAFE"
      | "USDC"
      | "distributeETH"
      | "distributeToken"
      | "distributeUSDC"
      | "getAddress"
      | "pendingETH"
      | "pendingToken"
      | "pendingUSDC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Distribution" | "RouterDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_SAFE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "distributeETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingUSDC",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_SAFE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pendingETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingUSDC",
    data: BytesLike
  ): Result;
}

export namespace DistributionEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, recipient: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterDeployedEvent {
  export type InputTuple = [Safe: AddressLike, deployer: AddressLike];
  export type OutputTuple = [Safe: string, deployer: string];
  export interface OutputObject {
    Safe: string;
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Router100 extends BaseContract {
  connect(runner?: ContractRunner | null): Router100;
  waitForDeployment(): Promise<this>;

  interface: Router100Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _SAFE: TypedContractMethod<[], [string], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  distributeETH: TypedContractMethod<[], [void], "nonpayable">;

  distributeToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  distributeUSDC: TypedContractMethod<[], [void], "nonpayable">;

  getAddress: TypedContractMethod<[], [string], "view">;

  pendingETH: TypedContractMethod<[], [bigint], "view">;

  pendingToken: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  pendingUSDC: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_SAFE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeUSDC"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingToken"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingUSDC"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Distribution"
  ): TypedContractEvent<
    DistributionEvent.InputTuple,
    DistributionEvent.OutputTuple,
    DistributionEvent.OutputObject
  >;
  getEvent(
    key: "RouterDeployed"
  ): TypedContractEvent<
    RouterDeployedEvent.InputTuple,
    RouterDeployedEvent.OutputTuple,
    RouterDeployedEvent.OutputObject
  >;

  filters: {
    "Distribution(address,uint256,address)": TypedContractEvent<
      DistributionEvent.InputTuple,
      DistributionEvent.OutputTuple,
      DistributionEvent.OutputObject
    >;
    Distribution: TypedContractEvent<
      DistributionEvent.InputTuple,
      DistributionEvent.OutputTuple,
      DistributionEvent.OutputObject
    >;

    "RouterDeployed(address,address)": TypedContractEvent<
      RouterDeployedEvent.InputTuple,
      RouterDeployedEvent.OutputTuple,
      RouterDeployedEvent.OutputObject
    >;
    RouterDeployed: TypedContractEvent<
      RouterDeployedEvent.InputTuple,
      RouterDeployedEvent.OutputTuple,
      RouterDeployedEvent.OutputObject
    >;
  };
}
