/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DAOTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "activateStateB"
      | "advanceEpoch"
      | "aiApiCap"
      | "currentEpoch"
      | "daoId"
      | "deadManSwitch"
      | "drawApiCap"
      | "drawFounderSurvival"
      | "drawHardware"
      | "drawPower"
      | "epochApiDrawn"
      | "epochDuration"
      | "epochFounderDrawn"
      | "epochHardwareDrawn"
      | "epochInfo"
      | "epochPowerDrawn"
      | "epochStart"
      | "founderSurvival"
      | "founderWallet"
      | "gnosisSafe"
      | "hardwareReserve"
      | "monthlySinkingTotal"
      | "owner"
      | "powerReserve"
      | "recordDeposit"
      | "remainingSinkingNeed"
      | "renounceOwnership"
      | "routeSurplus"
      | "setFounderWallet"
      | "setStakingVault"
      | "stakingVault"
      | "stateBActive"
      | "surplusAvailable"
      | "totalBalance"
      | "totalReceived"
      | "totalToFounder"
      | "totalToStaking"
      | "transferOwnership"
      | "updateSinkingFund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApiDraw"
      | "EpochAdvanced"
      | "FounderDraw"
      | "HardwareDraw"
      | "OwnershipTransferred"
      | "PowerDraw"
      | "Received"
      | "SinkingFundUpdated"
      | "StakingVaultSet"
      | "StateBActivated"
      | "SurplusToStaking"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activateStateB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "advanceEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aiApiCap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "daoId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deadManSwitch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawApiCap",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawFounderSurvival",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drawHardware",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawPower",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "epochApiDrawn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochFounderDrawn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochHardwareDrawn",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "epochInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "epochPowerDrawn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "founderSurvival",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "founderWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisSafe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hardwareReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monthlySinkingTotal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "powerReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingSinkingNeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routeSurplus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFounderWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateBActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "surplusAvailable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReceived",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalToFounder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalToStaking",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSinkingFund",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activateStateB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "advanceEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aiApiCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daoId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deadManSwitch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawApiCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drawFounderSurvival",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawHardware",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawPower", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochApiDrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochFounderDrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochHardwareDrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochPowerDrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochStart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "founderSurvival",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "founderWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gnosisSafe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hardwareReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlySinkingTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "powerReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingSinkingNeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeSurplus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFounderWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateBActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surplusAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalToFounder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalToStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSinkingFund",
    data: BytesLike
  ): Result;
}

export namespace ApiDrawEvent {
  export type InputTuple = [amount: BigNumberish, epoch: BigNumberish];
  export type OutputTuple = [amount: bigint, epoch: bigint];
  export interface OutputObject {
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochAdvancedEvent {
  export type InputTuple = [newEpoch: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newEpoch: bigint, timestamp: bigint];
  export interface OutputObject {
    newEpoch: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FounderDrawEvent {
  export type InputTuple = [amount: BigNumberish, epoch: BigNumberish];
  export type OutputTuple = [amount: bigint, epoch: bigint];
  export interface OutputObject {
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HardwareDrawEvent {
  export type InputTuple = [amount: BigNumberish, epoch: BigNumberish];
  export type OutputTuple = [amount: bigint, epoch: bigint];
  export interface OutputObject {
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PowerDrawEvent {
  export type InputTuple = [amount: BigNumberish, epoch: BigNumberish];
  export type OutputTuple = [amount: bigint, epoch: bigint];
  export interface OutputObject {
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivedEvent {
  export type InputTuple = [amount: BigNumberish, daoId: BytesLike];
  export type OutputTuple = [amount: bigint, daoId: string];
  export interface OutputObject {
    amount: bigint;
    daoId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SinkingFundUpdatedEvent {
  export type InputTuple = [
    founder: BigNumberish,
    api: BigNumberish,
    hardware: BigNumberish,
    power: BigNumberish
  ];
  export type OutputTuple = [
    founder: bigint,
    api: bigint,
    hardware: bigint,
    power: bigint
  ];
  export interface OutputObject {
    founder: bigint;
    api: bigint;
    hardware: bigint;
    power: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingVaultSetEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateBActivatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurplusToStakingEvent {
  export type InputTuple = [amount: BigNumberish, epoch: BigNumberish];
  export type OutputTuple = [amount: bigint, epoch: bigint];
  export interface OutputObject {
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DAOTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): DAOTreasury;
  waitForDeployment(): Promise<this>;

  interface: DAOTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  activateStateB: TypedContractMethod<[], [void], "nonpayable">;

  advanceEpoch: TypedContractMethod<[], [void], "nonpayable">;

  aiApiCap: TypedContractMethod<[], [bigint], "view">;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  daoId: TypedContractMethod<[], [string], "view">;

  deadManSwitch: TypedContractMethod<[], [string], "view">;

  drawApiCap: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  drawFounderSurvival: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  drawHardware: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  drawPower: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  epochApiDrawn: TypedContractMethod<[], [bigint], "view">;

  epochDuration: TypedContractMethod<[], [bigint], "view">;

  epochFounderDrawn: TypedContractMethod<[], [bigint], "view">;

  epochHardwareDrawn: TypedContractMethod<[], [bigint], "view">;

  epochInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        epoch: bigint;
        start: bigint;
        duration: bigint;
        founderRemaining: bigint;
        apiRemaining: bigint;
        hardwareRemaining: bigint;
        powerRemaining: bigint;
      }
    ],
    "view"
  >;

  epochPowerDrawn: TypedContractMethod<[], [bigint], "view">;

  epochStart: TypedContractMethod<[], [bigint], "view">;

  founderSurvival: TypedContractMethod<[], [bigint], "view">;

  founderWallet: TypedContractMethod<[], [string], "view">;

  gnosisSafe: TypedContractMethod<[], [string], "view">;

  hardwareReserve: TypedContractMethod<[], [bigint], "view">;

  monthlySinkingTotal: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  powerReserve: TypedContractMethod<[], [bigint], "view">;

  recordDeposit: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  remainingSinkingNeed: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routeSurplus: TypedContractMethod<[], [void], "nonpayable">;

  setFounderWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setStakingVault: TypedContractMethod<
    [_vault: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingVault: TypedContractMethod<[], [string], "view">;

  stateBActive: TypedContractMethod<[], [boolean], "view">;

  surplusAvailable: TypedContractMethod<[], [bigint], "view">;

  totalBalance: TypedContractMethod<[], [bigint], "view">;

  totalReceived: TypedContractMethod<[], [bigint], "view">;

  totalToFounder: TypedContractMethod<[], [bigint], "view">;

  totalToStaking: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSinkingFund: TypedContractMethod<
    [
      _founder: BigNumberish,
      _api: BigNumberish,
      _hardware: BigNumberish,
      _power: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activateStateB"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "advanceEpoch"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "aiApiCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "daoId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deadManSwitch"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "drawApiCap"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "drawFounderSurvival"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "drawHardware"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "drawPower"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochApiDrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochFounderDrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochHardwareDrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        epoch: bigint;
        start: bigint;
        duration: bigint;
        founderRemaining: bigint;
        apiRemaining: bigint;
        hardwareRemaining: bigint;
        powerRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "epochPowerDrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "founderSurvival"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "founderWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gnosisSafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hardwareReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "monthlySinkingTotal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "powerReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDeposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remainingSinkingNeed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routeSurplus"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFounderWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stateBActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "surplusAvailable"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReceived"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalToFounder"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalToStaking"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSinkingFund"
  ): TypedContractMethod<
    [
      _founder: BigNumberish,
      _api: BigNumberish,
      _hardware: BigNumberish,
      _power: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ApiDraw"
  ): TypedContractEvent<
    ApiDrawEvent.InputTuple,
    ApiDrawEvent.OutputTuple,
    ApiDrawEvent.OutputObject
  >;
  getEvent(
    key: "EpochAdvanced"
  ): TypedContractEvent<
    EpochAdvancedEvent.InputTuple,
    EpochAdvancedEvent.OutputTuple,
    EpochAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "FounderDraw"
  ): TypedContractEvent<
    FounderDrawEvent.InputTuple,
    FounderDrawEvent.OutputTuple,
    FounderDrawEvent.OutputObject
  >;
  getEvent(
    key: "HardwareDraw"
  ): TypedContractEvent<
    HardwareDrawEvent.InputTuple,
    HardwareDrawEvent.OutputTuple,
    HardwareDrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PowerDraw"
  ): TypedContractEvent<
    PowerDrawEvent.InputTuple,
    PowerDrawEvent.OutputTuple,
    PowerDrawEvent.OutputObject
  >;
  getEvent(
    key: "Received"
  ): TypedContractEvent<
    ReceivedEvent.InputTuple,
    ReceivedEvent.OutputTuple,
    ReceivedEvent.OutputObject
  >;
  getEvent(
    key: "SinkingFundUpdated"
  ): TypedContractEvent<
    SinkingFundUpdatedEvent.InputTuple,
    SinkingFundUpdatedEvent.OutputTuple,
    SinkingFundUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakingVaultSet"
  ): TypedContractEvent<
    StakingVaultSetEvent.InputTuple,
    StakingVaultSetEvent.OutputTuple,
    StakingVaultSetEvent.OutputObject
  >;
  getEvent(
    key: "StateBActivated"
  ): TypedContractEvent<
    StateBActivatedEvent.InputTuple,
    StateBActivatedEvent.OutputTuple,
    StateBActivatedEvent.OutputObject
  >;
  getEvent(
    key: "SurplusToStaking"
  ): TypedContractEvent<
    SurplusToStakingEvent.InputTuple,
    SurplusToStakingEvent.OutputTuple,
    SurplusToStakingEvent.OutputObject
  >;

  filters: {
    "ApiDraw(uint256,uint32)": TypedContractEvent<
      ApiDrawEvent.InputTuple,
      ApiDrawEvent.OutputTuple,
      ApiDrawEvent.OutputObject
    >;
    ApiDraw: TypedContractEvent<
      ApiDrawEvent.InputTuple,
      ApiDrawEvent.OutputTuple,
      ApiDrawEvent.OutputObject
    >;

    "EpochAdvanced(uint32,uint256)": TypedContractEvent<
      EpochAdvancedEvent.InputTuple,
      EpochAdvancedEvent.OutputTuple,
      EpochAdvancedEvent.OutputObject
    >;
    EpochAdvanced: TypedContractEvent<
      EpochAdvancedEvent.InputTuple,
      EpochAdvancedEvent.OutputTuple,
      EpochAdvancedEvent.OutputObject
    >;

    "FounderDraw(uint256,uint32)": TypedContractEvent<
      FounderDrawEvent.InputTuple,
      FounderDrawEvent.OutputTuple,
      FounderDrawEvent.OutputObject
    >;
    FounderDraw: TypedContractEvent<
      FounderDrawEvent.InputTuple,
      FounderDrawEvent.OutputTuple,
      FounderDrawEvent.OutputObject
    >;

    "HardwareDraw(uint256,uint32)": TypedContractEvent<
      HardwareDrawEvent.InputTuple,
      HardwareDrawEvent.OutputTuple,
      HardwareDrawEvent.OutputObject
    >;
    HardwareDraw: TypedContractEvent<
      HardwareDrawEvent.InputTuple,
      HardwareDrawEvent.OutputTuple,
      HardwareDrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PowerDraw(uint256,uint32)": TypedContractEvent<
      PowerDrawEvent.InputTuple,
      PowerDrawEvent.OutputTuple,
      PowerDrawEvent.OutputObject
    >;
    PowerDraw: TypedContractEvent<
      PowerDrawEvent.InputTuple,
      PowerDrawEvent.OutputTuple,
      PowerDrawEvent.OutputObject
    >;

    "Received(uint256,bytes32)": TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;
    Received: TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;

    "SinkingFundUpdated(uint64,uint64,uint64,uint64)": TypedContractEvent<
      SinkingFundUpdatedEvent.InputTuple,
      SinkingFundUpdatedEvent.OutputTuple,
      SinkingFundUpdatedEvent.OutputObject
    >;
    SinkingFundUpdated: TypedContractEvent<
      SinkingFundUpdatedEvent.InputTuple,
      SinkingFundUpdatedEvent.OutputTuple,
      SinkingFundUpdatedEvent.OutputObject
    >;

    "StakingVaultSet(address)": TypedContractEvent<
      StakingVaultSetEvent.InputTuple,
      StakingVaultSetEvent.OutputTuple,
      StakingVaultSetEvent.OutputObject
    >;
    StakingVaultSet: TypedContractEvent<
      StakingVaultSetEvent.InputTuple,
      StakingVaultSetEvent.OutputTuple,
      StakingVaultSetEvent.OutputObject
    >;

    "StateBActivated(uint256)": TypedContractEvent<
      StateBActivatedEvent.InputTuple,
      StateBActivatedEvent.OutputTuple,
      StateBActivatedEvent.OutputObject
    >;
    StateBActivated: TypedContractEvent<
      StateBActivatedEvent.InputTuple,
      StateBActivatedEvent.OutputTuple,
      StateBActivatedEvent.OutputObject
    >;

    "SurplusToStaking(uint256,uint32)": TypedContractEvent<
      SurplusToStakingEvent.InputTuple,
      SurplusToStakingEvent.OutputTuple,
      SurplusToStakingEvent.OutputObject
    >;
    SurplusToStaking: TypedContractEvent<
      SurplusToStakingEvent.InputTuple,
      SurplusToStakingEvent.OutputTuple,
      SurplusToStakingEvent.OutputObject
    >;
  };
}
