/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DatingRevenueRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "PCT_CHARITY"
      | "PCT_DAO"
      | "PCT_FOUNDER"
      | "USDC"
      | "charitySafe"
      | "daoTreasury"
      | "distributeETH"
      | "distributeToken"
      | "distributeUSDC"
      | "founderWallet"
      | "pendingETH"
      | "pendingToken"
      | "pendingUSDC"
      | "previewSplit"
      | "totalDistributed"
      | "totalDistributedETH"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Distribution" | "RouterDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PCT_CHARITY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PCT_DAO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PCT_FOUNDER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "charitySafe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daoTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "founderWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDistributedETH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PCT_CHARITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PCT_DAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PCT_FOUNDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "charitySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daoTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "founderWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pendingETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDistributedETH",
    data: BytesLike
  ): Result;
}

export namespace DistributionEvent {
  export type InputTuple = [
    token: AddressLike,
    totalAmount: BigNumberish,
    charityAmount: BigNumberish,
    daoAmount: BigNumberish,
    founderAmount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    totalAmount: bigint,
    charityAmount: bigint,
    daoAmount: bigint,
    founderAmount: bigint
  ];
  export interface OutputObject {
    token: string;
    totalAmount: bigint;
    charityAmount: bigint;
    daoAmount: bigint;
    founderAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterDeployedEvent {
  export type InputTuple = [
    charitySafe: AddressLike,
    daoTreasury: AddressLike,
    founderWallet: AddressLike,
    deployer: AddressLike
  ];
  export type OutputTuple = [
    charitySafe: string,
    daoTreasury: string,
    founderWallet: string,
    deployer: string
  ];
  export interface OutputObject {
    charitySafe: string;
    daoTreasury: string;
    founderWallet: string;
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DatingRevenueRouter extends BaseContract {
  connect(runner?: ContractRunner | null): DatingRevenueRouter;
  waitForDeployment(): Promise<this>;

  interface: DatingRevenueRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  PCT_CHARITY: TypedContractMethod<[], [bigint], "view">;

  PCT_DAO: TypedContractMethod<[], [bigint], "view">;

  PCT_FOUNDER: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  charitySafe: TypedContractMethod<[], [string], "view">;

  daoTreasury: TypedContractMethod<[], [string], "view">;

  distributeETH: TypedContractMethod<[], [void], "nonpayable">;

  distributeToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  distributeUSDC: TypedContractMethod<[], [void], "nonpayable">;

  founderWallet: TypedContractMethod<[], [string], "view">;

  pendingETH: TypedContractMethod<[], [bigint], "view">;

  pendingToken: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  pendingUSDC: TypedContractMethod<[], [bigint], "view">;

  previewSplit: TypedContractMethod<
    [amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        charityAmt: bigint;
        daoAmt: bigint;
        founderAmt: bigint;
      }
    ],
    "view"
  >;

  totalDistributed: TypedContractMethod<[], [bigint], "view">;

  totalDistributedETH: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PCT_CHARITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PCT_DAO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PCT_FOUNDER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "charitySafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "daoTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeUSDC"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "founderWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingToken"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingUSDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewSplit"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        charityAmt: bigint;
        daoAmt: bigint;
        founderAmt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDistributedETH"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Distribution"
  ): TypedContractEvent<
    DistributionEvent.InputTuple,
    DistributionEvent.OutputTuple,
    DistributionEvent.OutputObject
  >;
  getEvent(
    key: "RouterDeployed"
  ): TypedContractEvent<
    RouterDeployedEvent.InputTuple,
    RouterDeployedEvent.OutputTuple,
    RouterDeployedEvent.OutputObject
  >;

  filters: {
    "Distribution(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DistributionEvent.InputTuple,
      DistributionEvent.OutputTuple,
      DistributionEvent.OutputObject
    >;
    Distribution: TypedContractEvent<
      DistributionEvent.InputTuple,
      DistributionEvent.OutputTuple,
      DistributionEvent.OutputObject
    >;

    "RouterDeployed(address,address,address,address)": TypedContractEvent<
      RouterDeployedEvent.InputTuple,
      RouterDeployedEvent.OutputTuple,
      RouterDeployedEvent.OutputObject
    >;
    RouterDeployed: TypedContractEvent<
      RouterDeployedEvent.InputTuple,
      RouterDeployedEvent.OutputTuple,
      RouterDeployedEvent.OutputObject
    >;
  };
}
