/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GospelDonationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHARITY_PERCENT"
      | "FOUNDER_PERCENT"
      | "INFRASTRUCTURE_PERCENT"
      | "PERCENT_DENOMINATOR"
      | "calculateSplit"
      | "charityWallet"
      | "donateEth"
      | "donationCount"
      | "donorEthContributions"
      | "donorUsdcContributions"
      | "founderWallet"
      | "getDonorContributions"
      | "getGospelSplit"
      | "getTotalDonations"
      | "infrastructureWallet"
      | "owner"
      | "pause"
      | "paused"
      | "receiveCryptoDonation"
      | "renounceOwnership"
      | "rescueTokens"
      | "totalEthDonations"
      | "totalUsdcDonations"
      | "transferOwnership"
      | "unpause"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EthDonationReceived"
      | "GospelSplitExecuted"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
      | "UsdcDonationReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHARITY_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FOUNDER_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INFRASTRUCTURE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERCENT_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "charityWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "donateEth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "donationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donorEthContributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "donorUsdcContributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "founderWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDonorContributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGospelSplit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDonations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "infrastructureWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveCryptoDonation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEthDonations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsdcDonations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CHARITY_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FOUNDER_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INFRASTRUCTURE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERCENT_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "charityWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donateEth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donorEthContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donorUsdcContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "founderWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonorContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGospelSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "infrastructureWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveCryptoDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEthDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUsdcDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace EthDonationReceivedEvent {
  export type InputTuple = [
    donor: AddressLike,
    amount: BigNumberish,
    charityShare: BigNumberish,
    infrastructureShare: BigNumberish,
    founderShare: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    amount: bigint,
    charityShare: bigint,
    infrastructureShare: bigint,
    founderShare: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    donor: string;
    amount: bigint;
    charityShare: bigint;
    infrastructureShare: bigint;
    founderShare: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GospelSplitExecutedEvent {
  export type InputTuple = [
    tokenType: string,
    totalAmount: BigNumberish,
    charityAmount: BigNumberish,
    infrastructureAmount: BigNumberish,
    founderAmount: BigNumberish
  ];
  export type OutputTuple = [
    tokenType: string,
    totalAmount: bigint,
    charityAmount: bigint,
    infrastructureAmount: bigint,
    founderAmount: bigint
  ];
  export interface OutputObject {
    tokenType: string;
    totalAmount: bigint;
    charityAmount: bigint;
    infrastructureAmount: bigint;
    founderAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsdcDonationReceivedEvent {
  export type InputTuple = [
    donor: AddressLike,
    amount: BigNumberish,
    charityShare: BigNumberish,
    infrastructureShare: BigNumberish,
    founderShare: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    amount: bigint,
    charityShare: bigint,
    infrastructureShare: bigint,
    founderShare: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    donor: string;
    amount: bigint;
    charityShare: bigint;
    infrastructureShare: bigint;
    founderShare: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GospelDonation extends BaseContract {
  connect(runner?: ContractRunner | null): GospelDonation;
  waitForDeployment(): Promise<this>;

  interface: GospelDonationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHARITY_PERCENT: TypedContractMethod<[], [bigint], "view">;

  FOUNDER_PERCENT: TypedContractMethod<[], [bigint], "view">;

  INFRASTRUCTURE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  PERCENT_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  calculateSplit: TypedContractMethod<
    [amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        charityShare: bigint;
        infrastructureShare: bigint;
        founderShare: bigint;
      }
    ],
    "view"
  >;

  charityWallet: TypedContractMethod<[], [string], "view">;

  donateEth: TypedContractMethod<[], [void], "payable">;

  donationCount: TypedContractMethod<[], [bigint], "view">;

  donorEthContributions: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  donorUsdcContributions: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  founderWallet: TypedContractMethod<[], [string], "view">;

  getDonorContributions: TypedContractMethod<
    [donor: AddressLike],
    [[bigint, bigint] & { ethAmount: bigint; usdcAmount: bigint }],
    "view"
  >;

  getGospelSplit: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        charity: bigint;
        infrastructure: bigint;
        founder: bigint;
      }
    ],
    "view"
  >;

  getTotalDonations: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        ethTotal: bigint;
        usdcTotal: bigint;
        count: bigint;
      }
    ],
    "view"
  >;

  infrastructureWallet: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  receiveCryptoDonation: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueTokens: TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  totalEthDonations: TypedContractMethod<[], [bigint], "view">;

  totalUsdcDonations: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHARITY_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FOUNDER_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INFRASTRUCTURE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PERCENT_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateSplit"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        charityShare: bigint;
        infrastructureShare: bigint;
        founderShare: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "charityWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "donateEth"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "donationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "donorEthContributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "donorUsdcContributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "founderWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDonorContributions"
  ): TypedContractMethod<
    [donor: AddressLike],
    [[bigint, bigint] & { ethAmount: bigint; usdcAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGospelSplit"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        charity: bigint;
        infrastructure: bigint;
        founder: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalDonations"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        ethTotal: bigint;
        usdcTotal: bigint;
        count: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "infrastructureWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "receiveCryptoDonation"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalEthDonations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsdcDonations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EthDonationReceived"
  ): TypedContractEvent<
    EthDonationReceivedEvent.InputTuple,
    EthDonationReceivedEvent.OutputTuple,
    EthDonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "GospelSplitExecuted"
  ): TypedContractEvent<
    GospelSplitExecutedEvent.InputTuple,
    GospelSplitExecutedEvent.OutputTuple,
    GospelSplitExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UsdcDonationReceived"
  ): TypedContractEvent<
    UsdcDonationReceivedEvent.InputTuple,
    UsdcDonationReceivedEvent.OutputTuple,
    UsdcDonationReceivedEvent.OutputObject
  >;

  filters: {
    "EthDonationReceived(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      EthDonationReceivedEvent.InputTuple,
      EthDonationReceivedEvent.OutputTuple,
      EthDonationReceivedEvent.OutputObject
    >;
    EthDonationReceived: TypedContractEvent<
      EthDonationReceivedEvent.InputTuple,
      EthDonationReceivedEvent.OutputTuple,
      EthDonationReceivedEvent.OutputObject
    >;

    "GospelSplitExecuted(string,uint256,uint256,uint256,uint256)": TypedContractEvent<
      GospelSplitExecutedEvent.InputTuple,
      GospelSplitExecutedEvent.OutputTuple,
      GospelSplitExecutedEvent.OutputObject
    >;
    GospelSplitExecuted: TypedContractEvent<
      GospelSplitExecutedEvent.InputTuple,
      GospelSplitExecutedEvent.OutputTuple,
      GospelSplitExecutedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UsdcDonationReceived(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UsdcDonationReceivedEvent.InputTuple,
      UsdcDonationReceivedEvent.OutputTuple,
      UsdcDonationReceivedEvent.OutputObject
    >;
    UsdcDonationReceived: TypedContractEvent<
      UsdcDonationReceivedEvent.InputTuple,
      UsdcDonationReceivedEvent.OutputTuple,
      UsdcDonationReceivedEvent.OutputObject
    >;
  };
}
