/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deadManSwitchSol from "./DeadManSwitch.sol";
export type { deadManSwitchSol };
import type * as governance from "./governance";
export type { governance };
import type * as test from "./test";
export type { test };
export type { Router100 } from "./Router100";
export type { DAOTreasury } from "./DAOTreasury";
export type { DatingRevenueRouter } from "./DatingRevenueRouter";
export type { Gospelpayment } from "./Gospelpayment";
export type { MissionTreasury } from "./MissionTreasury";
export type { PlatformSplitter } from "./PlatformSplitter";
export type { PlatformSplitter10 } from "./PlatformSplitter10";
export type { SoulboundToken } from "./SoulboundToken";
