/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PlatformSplitter10Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "MISSION_BPS"
      | "USDC"
      | "bucketId"
      | "missionTreasury"
      | "operatingWallet"
      | "pendingUSDC"
      | "platformName"
      | "previewSplit"
      | "splitToken"
      | "splitUSDC"
      | "totalProcessed"
      | "totalToMission"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Split"): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MISSION_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "bucketId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "missionTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operatingWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "splitToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "splitUSDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalProcessed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalToMission",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MISSION_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bucketId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "missionTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operatingWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "splitUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalToMission",
    data: BytesLike
  ): Result;
}

export namespace SplitEvent {
  export type InputTuple = [
    token: AddressLike,
    totalAmount: BigNumberish,
    missionAmount: BigNumberish,
    operatingAmount: BigNumberish,
    bucketId: string
  ];
  export type OutputTuple = [
    token: string,
    totalAmount: bigint,
    missionAmount: bigint,
    operatingAmount: bigint,
    bucketId: string
  ];
  export interface OutputObject {
    token: string;
    totalAmount: bigint;
    missionAmount: bigint;
    operatingAmount: bigint;
    bucketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlatformSplitter10 extends BaseContract {
  connect(runner?: ContractRunner | null): PlatformSplitter10;
  waitForDeployment(): Promise<this>;

  interface: PlatformSplitter10Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  MISSION_BPS: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  bucketId: TypedContractMethod<[], [string], "view">;

  missionTreasury: TypedContractMethod<[], [string], "view">;

  operatingWallet: TypedContractMethod<[], [string], "view">;

  pendingUSDC: TypedContractMethod<[], [bigint], "view">;

  platformName: TypedContractMethod<[], [string], "view">;

  previewSplit: TypedContractMethod<
    [amount: BigNumberish],
    [[bigint, bigint] & { mission: bigint; operating: bigint }],
    "view"
  >;

  splitToken: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  splitUSDC: TypedContractMethod<[], [void], "nonpayable">;

  totalProcessed: TypedContractMethod<[], [bigint], "view">;

  totalToMission: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MISSION_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bucketId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "missionTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operatingWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingUSDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewSplit"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [[bigint, bigint] & { mission: bigint; operating: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "splitToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splitUSDC"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalProcessed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalToMission"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Split"
  ): TypedContractEvent<
    SplitEvent.InputTuple,
    SplitEvent.OutputTuple,
    SplitEvent.OutputObject
  >;

  filters: {
    "Split(address,uint256,uint256,uint256,string)": TypedContractEvent<
      SplitEvent.InputTuple,
      SplitEvent.OutputTuple,
      SplitEvent.OutputObject
    >;
    Split: TypedContractEvent<
      SplitEvent.InputTuple,
      SplitEvent.OutputTuple,
      SplitEvent.OutputObject
    >;
  };
}
