# Bootstrap: CLAUDE's Antigravity — Paperclip-compatible server on port 3101
# Generated by Hermes (CEO agent)

$ErrorActionPreference = "Stop"
$ServerDir = "C:\income-engine\paperclip-server"
$EnvFile   = "C:\income-engine\.env.paperclip"

Write-Host "[Hermes] Bootstrapping CLAUDEs Antigravity on port 3101..." -ForegroundColor Cyan

# 1. Create server directory
if (-not (Test-Path $ServerDir)) {
    New-Item -ItemType Directory -Path $ServerDir | Out-Null
    Write-Host "[Hermes] Created $ServerDir"
}
Set-Location $ServerDir

# 2. Init npm project and install deps
if (-not (Test-Path "$ServerDir\package.json")) {
    npm init -y | Out-Null
    Write-Host "[Hermes] Initialized npm project"
}
npm install express uuid --save --silent
Write-Host "[Hermes] Dependencies installed"

# 3. Write server.js
$ServerJS = @'
const express = require('express');
const { v4: uuidv4 } = require('uuid');
const app = express();
app.use(express.json());

const companies = [];
const agents = [];

app.get('/health', (req, res) => res.json({ status: 'ok', service: 'paperclip-3101' }));

app.post('/api/companies', (req, res) => {
  const company = { id: uuidv4(), name: req.body.name || 'CLAUDEs Antigravity', apiKey: uuidv4() };
  companies.push(company);
  res.json(company);
});

app.get('/api/companies', (req, res) => res.json(companies));

app.post('/api/agents', (req, res) => {
  const agent = { id: uuidv4(), name: req.body.name, role: req.body.role, companyId: req.body.companyId, status: 'active' };
  agents.push(agent);
  res.json(agent);
});

app.get('/api/companies/:id/agents', (req, res) => {
  res.json(agents.filter(a => a.companyId === req.params.id));
});

app.get('/api/agents/:id', (req, res) => {
  const agent = agents.find(a => a.id === req.params.id);
  if (!agent) return res.status(404).json({ error: 'Not found' });
  res.json(agent);
});

app.post('/api/agents/:id/heartbeat', (req, res) => {
  const agent = agents.find(a => a.id === req.params.id);
  if (agent) agent.lastHeartbeat = new Date().toISOString();
  res.json({ ok: true });
});

app.listen(3101, () => console.log('[Paperclip-3101] Running on port 3101'));
'@

Set-Content -Path "$ServerDir\server.js" -Value $ServerJS
Write-Host "[Hermes] server.js written"

# 4. Start server
$pm2Available = Get-Command pm2 -ErrorAction SilentlyContinue
if ($pm2Available) {
    pm2 start "$ServerDir\server.js" --name "paperclip-3101" 2>$null
    Write-Host "[Hermes] Started via pm2"
} else {
    Start-Process -FilePath "node" -ArgumentList "$ServerDir\server.js" -WindowStyle Hidden
    Write-Host "[Hermes] Started as background process"
}

# 5. Wait for startup
Write-Host "[Hermes] Waiting for server..." -ForegroundColor Yellow
Start-Sleep -Seconds 5

# 6. Create company
Write-Host "[Hermes] Creating company..."
try {
    $company = Invoke-RestMethod -Method POST -Uri "http://localhost:3101/api/companies" `
        -ContentType "application/json" `
        -Body '{"name":"CLAUDEs Antigravity"}'
    $companyId = $company.id
    $apiKey    = $company.apiKey
    Write-Host "[Hermes] Company created: $companyId" -ForegroundColor Green
} catch {
    Write-Warning "[Hermes] Failed to create company: $_"
    exit 1
}

# 7. Register agents
Write-Host "[Hermes] Registering CEO agent..."
$ceoBody = "{`"name`":`"ceo-income`",`"role`":`"CEO`",`"companyId`":`"$companyId`"}"
$ceo = Invoke-RestMethod -Method POST -Uri "http://localhost:3101/api/agents" `
    -ContentType "application/json" -Body $ceoBody
Write-Host "[Hermes] CEO agent: $($ceo.id)"

Write-Host "[Hermes] Registering FETCHER agent..."
$fetcherBody = "{`"name`":`"fetcher`",`"role`":`"Lead Scanner`",`"companyId`":`"$companyId`"}"
$fetcher = Invoke-RestMethod -Method POST -Uri "http://localhost:3101/api/agents" `
    -ContentType "application/json" -Body $fetcherBody
Write-Host "[Hermes] FETCHER agent: $($fetcher.id)"

# 8. Print results
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  CLAUDE's Antigravity — Bootstrap Done" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  PAPERCLIP_URL       = http://localhost:3100"
Write-Host "  PAPERCLIP_COMPANY_ID = $companyId"
Write-Host "  PAPERCLIP_API_KEY   = $apiKey"
Write-Host "  CEO Agent ID        = $($ceo.id)"
Write-Host "  FETCHER Agent ID    = $($fetcher.id)"
Write-Host "========================================" -ForegroundColor Cyan

# 9. Write .env.paperclip
$envContent = @"
PAPERCLIP_URL=http://localhost:3101
PAPERCLIP_COMPANY_ID=$companyId
PAPERCLIP_API_KEY=$apiKey
PAPERCLIP_CEO_AGENT_ID=$($ceo.id)
PAPERCLIP_FETCHER_AGENT_ID=$($fetcher.id)
"@

Set-Content -Path $EnvFile -Value $envContent
Write-Host "[Hermes] Credentials saved to $EnvFile" -ForegroundColor Green
Write-Host "[Hermes] Bootstrap complete. Add .env.paperclip values to your main .env" -ForegroundColor Green
