$ErrorActionPreference = 'Stop'
$RepoRoot = 'C:\ANTIGRAVITY'
$ToolsMd  = "C:\ANTIGRAVITY\paperclip\agents\ceo\TOOLS.md"
Set-Location $RepoRoot

function OK($m)   { Write-Host "[OK]   $m" -ForegroundColor Green }
function FAIL($m) { Write-Host "[FAIL] $m" -ForegroundColor Red }
function INFO($m) { Write-Host "[INFO] $m" -ForegroundColor Cyan }
function WARN($m) { Write-Host "[WARN] $m" -ForegroundColor Yellow }

Write-Host "`n=== 02-fix-hermes-config.ps1 ===" -ForegroundColor Cyan

# ── 1. Detect canonical config path ──────────────────────────────────────────
$candidates = @(
  "C:\Users\joshl\.hermes\config.yaml",
  "C:\Users\joshl\AppData\Local\hermes\config.yaml"
)
$configPath = $null
foreach ($p in $candidates) {
  if (Test-Path $p) {
    if ($null -eq $configPath) { $configPath = $p }
    else { WARN "Both config paths exist: $p  AND  $configPath — using first found: $configPath" }
  }
}

if ($null -eq $configPath) {
  WARN "No Hermes config found at either candidate path."
  WARN "Writing minimal default config at C:\Users\joshl\.hermes\config.yaml"

  $configPath = "C:\Users\joshl\.hermes\config.yaml"
  $dir = Split-Path $configPath
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

  @"
# Hermes CEO — canonical config
# Generated by ANTIGRAVITY deploy package 2026-04-21
# Sole authority: Joshua Coleman

model: glm-5.1
provider: ollama-cloud
base_url: https://ollama.com/v1

identity: C:\Users\joshl\.hermes\SOUL.md

fallbacks:
  - model: qwen2.5:7b
    provider: ollama
    base_url: http://127.0.0.1:11434/v1
"@ | Set-Content $configPath -Encoding UTF8
  OK "Created default config at $configPath"
} else {
  OK "Active Hermes config: $configPath"
}

# ── 2. Read + display config ──────────────────────────────────────────────────
INFO "Current config.yaml contents:"
Get-Content $configPath | ForEach-Object { Write-Host "  $_" }

# Parse primary model + provider from config
$configContent = Get-Content $configPath -Raw
$modelMatch    = [regex]::Match($configContent, '(?m)^model:\s*(.+)$')
$providerMatch = [regex]::Match($configContent, '(?m)^provider:\s*(.+)$')
$liveModel    = if ($modelMatch.Success)    { $modelMatch.Groups[1].Value.Trim() }    else { "unknown" }
$liveProvider = if ($providerMatch.Success) { $providerMatch.Groups[1].Value.Trim() } else { "unknown" }

INFO "Detected: model=$liveModel  provider=$liveProvider"

# ── 3. Validate model responds ───────────────────────────────────────────────
INFO "Testing Hermes CEO model response..."
$hermesOk = $false
try {
  $output = & hermes run "Reply with the single word OK and nothing else." 2>&1
  if ($output -match 'OK') {
    OK "Hermes model responded: $($output -join ' ')"
    $hermesOk = $true
  } else {
    WARN "Hermes responded but output unexpected: $($output -join ' ')"
    $hermesOk = $true  # responded = alive, even if verbose
  }
} catch {
  WARN "Hermes run failed: $($_.Exception.Message)"
}

# ── 4. Fallback: switch to glm-5.1 / ollama-cloud if primary failed ──────────
if (-not $hermesOk) {
  WARN "Primary model failed. Patching config to glm-5.1 / ollama-cloud..."
  $configContent = $configContent -replace '(?m)^(model:\s*).*$',  '${1}glm-5.1'
  $configContent = $configContent -replace '(?m)^(provider:\s*).*$', '${1}ollama-cloud'
  $configContent = $configContent -replace '(?m)^(base_url:\s*).*$', '${1}https://ollama.com/v1'
  Set-Content $configPath $configContent -Encoding UTF8
  $liveModel    = "glm-5.1"
  $liveProvider = "ollama-cloud"

  INFO "Retesting after patch..."
  try {
    $output = & hermes run "Reply with the single word OK and nothing else." 2>&1
    if ($output) { OK "Hermes now responds on fallback: $($output -join ' ')"; $hermesOk = $true }
  } catch {
    FAIL "Hermes still unresponsive after fallback patch: $($_.Exception.Message)"
    FAIL "Manual intervention required. Check OpenClaw / Ollama service."
    exit 1
  }
}

# ── 5. Sync TOOLS.md ## Model section to validated live config ────────────────
INFO "Updating TOOLS.md ## Model section to match live config..."
if (-not (Test-Path $ToolsMd)) {
  FAIL "TOOLS.md not found at $ToolsMd"
  exit 1
}

$tools = Get-Content $ToolsMd -Raw

# Build the correct model line
$newModelLine = "ollama/$liveModel via $liveProvider."
if ($liveModel -eq "glm-5.1" -or $liveModel -eq "glm-5.1:cloud") {
  $newModelLine = "ollama/glm-5.1:cloud via ollama-cloud (https://ollama.com/v1). 138K context, tools, thinking. No Anthropic API tokens consumed.`nFallback: ollama/qwen2.5:7b local via Ollama if cloud unavailable."
} elseif ($liveModel -match "korpohermes") {
  $newModelLine = "ollama/$liveModel via OpenClaw (127.0.0.1:18789). Cloud-routed.`nFallback 1: ollama/glm-5.1:cloud via ollama-cloud (138K context)`nFallback 2: ollama/qwen2.5:7b local"
}

# Replace the ## Model section (everything from ## Model to next ##)
$tools = $tools -replace '(?s)(## Model\r?\n).*?(\r?\n## |\z)', "## Model`n$newModelLine`n`n`$2"
# Clean up double ## from replacement
$tools = $tools -replace "(`n`n## )", "`n`n## "

Set-Content $ToolsMd $tools -Encoding UTF8
OK "TOOLS.md ## Model section updated: $liveModel / $liveProvider"

# ── 6. Canonical path note ────────────────────────────────────────────────────
if ($candidates[1] -and (Test-Path $candidates[1]) -and $configPath -ne $candidates[1]) {
  WARN "Second config path also exists: $($candidates[1])"
  WARN "Consider deleting the non-canonical one to eliminate ambiguity:"
  WARN "  Remove-Item '$($candidates[1])'"
}

Write-Host "`n[DONE] 02-fix-hermes-config.ps1 complete" -ForegroundColor Green
exit 0
