/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ReentrancyAttacker,
  ReentrancyAttackerInterface,
} from "../../../src/test/ReentrancyAttacker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attackCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "target",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b5060405161022f38038061022f833981016040819052602b91604e565b5f80546001600160a01b0319166001600160a01b03929092169190911790556079565b5f60208284031215605d575f5ffd5b81516001600160a01b03811681146072575f5ffd5b9392505050565b6101a9806100865f395ff3fe60806040526004361061002b575f3560e01c8063407c2821146100db578063d4b8399214610103575f5ffd5b366100d75760018054905f61003f83610139565b9190505550600360015410156100d5575f805460408051600481526024810182526020810180516001600160e01b031663b8b9b54960e01b17905290516001600160a01b0390921691610092919061015d565b5f604051808303815f865af19150503d805f81146100cb576040519150601f19603f3d011682016040523d82523d5f602084013e6100d0565b606091505b505050505b005b5f5ffd5b3480156100e6575f5ffd5b506100f060015481565b6040519081526020015b60405180910390f35b34801561010e575f5ffd5b505f54610121906001600160a01b031681565b6040516001600160a01b0390911681526020016100fa565b5f6001820161015657634e487b7160e01b5f52601160045260245ffd5b5060010190565b5f82518060208501845e5f92019182525091905056fea2646970667358221220f047ee6ac6712addecc11df0e8896b844881f6db4f3203b895ad11ea69a49f7664736f6c634300081c0033";

type ReentrancyAttackerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyAttackerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyAttacker__factory extends ContractFactory {
  constructor(...args: ReentrancyAttackerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_target, overrides || {});
  }
  override deploy(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_target, overrides || {}) as Promise<
      ReentrancyAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrancyAttacker__factory {
    return super.connect(runner) as ReentrancyAttacker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAttackerInterface {
    return new Interface(_abi) as ReentrancyAttackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyAttacker {
    return new Contract(address, _abi, runner) as unknown as ReentrancyAttacker;
  }
}
