"""
Idempotency key middleware for Mission Control API.

Supports the Idempotency-Key header on POST / PUT / PATCH requests to prevent
duplicate operations when clients retry.  Stored responses are kept in memory
and expire after 24 hours.

Usage:
    app.add_middleware(IdempotencyMiddleware)

Design decisions:
    - Pure stdlib — no external dependencies.
    - In-memory dict mapping idempotency key → (body, status, headers, expires_at).
    - Keys expire after 24 hours (timestamp-based lazy eviction + periodic cleanup).
    - Only applies to mutating methods (POST, PUT, PATCH).
    - The Idempotency-Key value is expected to be a UUID or similar unique token
      generated by the client.  The same key + same request path is treated as the
      same logical operation.
"""

from __future__ import annotations

import json
import time
import threading
from typing import Tuple, Dict, Optional

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response, JSONResponse

from mission_control_api.logging_config import get_logger

logger = get_logger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────

IDEMPOTENCY_KEY_HEADER = "Idempotency-Key"
IDEMPOTENCY_EXPIRE_SECONDS = 24 * 60 * 60  # 24 hours
CLEANUP_INTERVAL_SECONDS = 600  # run cleanup every 10 minutes

# ── In-memory store ────────────────────────────────────────────────────────────

# Maps "key:path" → (response_body: bytes, status_code: int, headers: dict, expires_at: float)
_idempotency_store: Dict[str, Tuple[bytes, int, dict, float]] = {}
_store_lock = threading.Lock()
_last_cleanup = time.time()


def _make_cache_key(idempotency_key: str, path: str) -> str:
    """Build a composite cache key from the idempotency key and request path."""
    return f"{idempotency_key}:{path}"


def _cleanup_expired() -> int:
    """Remove expired entries from the store. Returns the number removed."""
    now = time.time()
    expired_keys = [k for k, v in _idempotency_store.items() if v[3] <= now]
    for k in expired_keys:
        del _idempotency_store[k]
    return len(expired_keys)


def get_idempotency_stats() -> dict:
    """Return current store statistics (for diagnostics)."""
    with _store_lock:
        return {
            "stored_keys": len(_idempotency_store),
            "expire_seconds": IDEMPOTENCY_EXPIRE_SECONDS,
        }


class IdempotencyMiddleware(BaseHTTPMiddleware):
    """
    FastAPI middleware that implements idempotency-key semantics.

    On POST / PUT / PATCH requests carrying an Idempotency-Key header:
      1. If the key has been seen before for the same path and the stored
         response has not expired, return the cached response immediately.
      2. Otherwise, forward the request, cache the response, and return it.

    GET / DELETE requests pass through without any idempotency logic.
    """

    MUTATING_METHODS = frozenset({"POST", "PUT", "PATCH"})

    async def dispatch(self, request: Request, call_next) -> Response:
        global _last_cleanup

        method = request.method.upper()

        # Only apply idempotency to mutating methods
        if method not in self.MUTATING_METHODS:
            return await call_next(request)

        idempotency_key = request.headers.get(IDEMPOTENCY_KEY_HEADER)

        # No idempotency key — just forward the request normally
        if not idempotency_key:
            return await call_next(request)

        # Validate the key is non-empty and reasonable length
        idempotency_key = idempotency_key.strip()
        if not idempotency_key or len(idempotency_key) > 256:
            logger.warning(
                "invalid idempotency key",
                extra={
                    "path": request.url.path,
                    "method": method,
                    "key_length": len(idempotency_key) if idempotency_key else 0,
                },
            )
            return JSONResponse(
                status_code=400,
                content={
                    "detail": "Invalid Idempotency-Key header. "
                              "Must be a non-empty string up to 256 characters."
                },
            )

        cache_key = _make_cache_key(idempotency_key, request.url.path)

        # ── Check cache ──────────────────────────────────────────────────────
        with _store_lock:
            cached = _idempotency_store.get(cache_key)
            if cached is not None:
                body, status_code, headers, expires_at = cached
                if time.time() < expires_at:
                    logger.info(
                        "idempotency cache hit",
                        extra={
                            "path": request.url.path,
                            "method": method,
                            "cache_key": cache_key,
                            "status_code": status_code,
                        },
                    )
                    # Return the cached response
                    response_headers = {k: v for k, v in headers.items()
                                        if k.lower() not in ("content-length", "transfer-encoding")}
                    response = Response(
                        content=body,
                        status_code=status_code,
                        headers=response_headers,
                        media_type="application/json",
                    )
                    response.headers["X-Idempotency-Replay"] = "true"
                    return response
                else:
                    # Expired — remove and continue
                    del _idempotency_store[cache_key]
                    logger.info(
                        "idempotency cache expired",
                        extra={"cache_key": cache_key},
                    )

        # ── Forward the request ──────────────────────────────────────────────
        response = await call_next(request)

        # ── Cache the response ───────────────────────────────────────────────
        # Read the response body
        response_body = b""
        if hasattr(response, "body"):
            try:
                response_body = await response.body
            except Exception:
                response_body = b""

        # Only cache successful responses (2xx) and client errors (4xx)
        # Don't cache 5xx — the client may want to retry after a server error
        if 200 <= response.status_code < 500:
            expires_at = time.time() + IDEMPOTENCY_EXPIRE_SECONDS
            response_headers = {k: v for k, v in response.headers.items()}

            with _store_lock:
                _idempotency_store[cache_key] = (
                    response_body,
                    response.status_code,
                    response_headers,
                    expires_at,
                )
                logger.info(
                    "idempotency cache store",
                    extra={
                        "path": request.url.path,
                        "method": method,
                        "cache_key": cache_key,
                        "status_code": response.status_code,
                        "expires_at": expires_at,
                    },
                )

                # Periodic cleanup of expired entries
                now = time.time()
                if now - _last_cleanup > CLEANUP_INTERVAL_SECONDS:
                    removed = _cleanup_expired()
                    _last_cleanup = now
                    if removed:
                        logger.info(
                            "idempotency cleanup",
                            extra={"removed": removed, "remaining": len(_idempotency_store)},
                        )

        return response
