import { OperationsPage } from "@/components/OperationsPage";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { FileCheck2, Loader2, PackagePlus, Search } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { FormEvent, useState } from "react";

export default function Catalog() {
  const utils = trpc.useUtils();
  const catalog = trpc.catalog.list.useQuery();
  const [form, setForm] = useState({ sku: "", upc: "", title: "", condition: "Good", brandOrStudio: "", format: "DVD", description: "" });
  const create = trpc.catalog.create.useMutation({ onSuccess: () => { utils.catalog.list.invalidate(); utils.operations.overview.invalidate(); setForm({ sku: "", upc: "", title: "", condition: "Good", brandOrStudio: "", format: "DVD", description: "" }); } });
  const verify = trpc.catalog.verify.useMutation({ onSuccess: () => { utils.catalog.list.invalidate(); utils.operations.overview.invalidate(); } });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ ...form, upc: form.upc || undefined, brandOrStudio: form.brandOrStudio || undefined, format: form.format || undefined, description: form.description || undefined }); };
  return <OperationsPage eyebrow="Canonical records" title="Catalog control" description="Create and verify the product records that drive every channel payload. Unverified records cannot pass listing preflight.">
    <div className="grid gap-5 xl:grid-cols-[1.55fr_0.85fr]">
      <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div><h2 className="text-lg font-semibold">New catalog record</h2><p className="mt-1 text-sm text-muted-foreground">Enter confirmed information only. Inventory begins at zero until it is received through the ledger.</p></div><form onSubmit={submit} className="mt-6 grid gap-3 sm:grid-cols-2"><input required value={form.sku} onChange={event => setForm({ ...form, sku: event.target.value })} placeholder="SKU" className="h-10 rounded-lg border border-input bg-background px-3 text-sm"/><input value={form.upc} onChange={event => setForm({ ...form, upc: event.target.value })} placeholder="UPC (optional)" className="h-10 rounded-lg border border-input bg-background px-3 text-sm"/><input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Verified product title" className="h-10 rounded-lg border border-input bg-background px-3 text-sm sm:col-span-2"/><select value={form.condition} onChange={event => setForm({ ...form, condition: event.target.value })} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option>New</option><option>Like New</option><option>Very Good</option><option>Good</option><option>Acceptable</option></select><input value={form.format} onChange={event => setForm({ ...form, format: event.target.value })} placeholder="Format" className="h-10 rounded-lg border border-input bg-background px-3 text-sm"/><input value={form.brandOrStudio} onChange={event => setForm({ ...form, brandOrStudio: event.target.value })} placeholder="Brand or studio" className="h-10 rounded-lg border border-input bg-background px-3 text-sm sm:col-span-2"/><textarea value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Factual description (optional)" className="min-h-24 rounded-lg border border-input bg-background px-3 py-2 text-sm sm:col-span-2"/><div className="sm:col-span-2"><Button disabled={create.isPending} className="gap-2">{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <PackagePlus className="h-4 w-4"/>} Create record</Button>{create.error ? <p className="mt-2 text-sm text-destructive">{create.error.message}</p> : null}</div></form></section>
      <aside className="rounded-2xl bg-slate-950 p-6 text-slate-50 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Verification rule</p><FileCheck2 className="mt-6 h-9 w-9 text-emerald-300" /><h2 className="mt-5 text-xl font-semibold">Facts before draft copy</h2><p className="mt-3 text-sm leading-6 text-slate-300">Titles, condition, item specifics, media, and descriptions must be supported by the catalog record. AI assistance can draft language but cannot add product facts.</p><Badge className="mt-6 bg-emerald-400/15 text-emerald-200 hover:bg-emerald-400/15">Review required</Badge></aside>
    </div>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Catalog queue</h2><p className="mt-1 text-sm text-muted-foreground">Verify records before sending them to the listing desk.</p></div><Badge variant="outline">{catalog.data?.length ?? 0} records</Badge></div>{catalog.isLoading ? <div className="mt-8 flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/> Loading catalog</div> : catalog.data?.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-[0.12em] text-muted-foreground"><tr><th className="pb-3 font-medium">SKU</th><th className="pb-3 font-medium">Product</th><th className="pb-3 font-medium">Condition</th><th className="pb-3 font-medium">Verification</th><th className="pb-3"></th></tr></thead><tbody>{catalog.data.map(product => <tr key={product.id} className="border-b border-border/70 last:border-0"><td className="py-4 font-mono text-xs">{product.sku}</td><td className="py-4"><p className="font-medium">{product.title}</p><p className="mt-1 text-xs text-muted-foreground">{product.upc || "No UPC"} · {product.format || "No format"}</p></td><td className="py-4">{product.condition}</td><td className="py-4"><Badge variant={product.verificationStatus === "verified" ? "default" : "secondary"}>{product.verificationStatus === "verified" ? "Verified" : "Needs review"}</Badge></td><td className="py-4 text-right">{product.verificationStatus !== "verified" ? <Button size="sm" variant="outline" disabled={verify.isPending} onClick={() => verify.mutate({ productId: product.id })}>Verify</Button> : null}</td></tr>)}</tbody></table></div> : <div className="mt-8 flex min-h-40 flex-col items-center justify-center rounded-xl border border-dashed border-border bg-muted/20 p-8 text-center"><Search className="h-8 w-8 text-muted-foreground/70" /><h3 className="mt-4 font-medium">No catalog records yet</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Create a verified product record to begin a controlled marketplace workflow.</p></div>}</section>
  </OperationsPage>;
}
