import { OperationsPage } from "@/components/OperationsPage";
import { AlertTriangle, CircleCheck, Loader2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";

export default function Exceptions() {
  const exceptions = trpc.exceptions.listOpen.useQuery();
  return <OperationsPage eyebrow="Audit and resolution" title="Exception queue" description="Incomplete records, unsupported channel actions, failed submissions, inventory conflicts, and security checks are routed here for an accountable resolution.">
    <section className="grid gap-5 lg:grid-cols-[1.3fr_0.7fr]"><div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Open work</h2><p className="mt-1 text-sm text-muted-foreground">Every blocked listing or inventory action is retained with its exact reason.</p></div><Badge variant="outline">{exceptions.data?.length ?? 0} open</Badge></div>{exceptions.isLoading ? <div className="mt-6 flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading queue</div> : exceptions.data?.length ? <div className="mt-6 space-y-3">{exceptions.data.map(item => <div key={item.id} className="rounded-xl border border-border bg-muted/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{item.message}</p><p className="mt-1 text-sm text-muted-foreground">{item.category} · subject {item.subjectType} #{item.subjectId}</p></div><Badge variant={item.severity === "high" || item.severity === "critical" ? "destructive" : "secondary"}>{item.severity}</Badge></div><p className="mt-3 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></div>)}</div> : <div className="mt-6 rounded-xl border border-dashed border-border bg-muted/20 p-6 text-sm leading-6 text-muted-foreground">No open exceptions. Guardrail blocks will be recorded here instead of being silently skipped.</div>}</div><div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><CircleCheck className="h-7 w-7 text-emerald-600" /><h2 className="mt-5 text-lg font-semibold">Audit-ready workflow</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Exception closure remains connected to the originating catalog, listing, inventory, or profile action.</p></div></section>
  </OperationsPage>;
}
