<# 
    Setup-OpusDrives.ps1
    Joshua / SABRETOOTH

    GOAL:
    - Do NOT touch system volumes C, D, F.
    - Treat:
        E:  = SABRETOOTH OPUS drive
        G:  = T5500 drive
        H:  = 9020 drive
    - On each of E, G, H create a consistent OPUSONLY layout.
    - On E: write a central node_manifest.json that maps:
        SABRETOOTH -> E:\OPUSONLY
        T5500      -> G:\OPUSONLY
        OPTIPLEX   -> H:\OPUSONLY
#>

Write-Host "=== OPUS DRIVE SETUP START ===" -ForegroundColor Cyan

# 1. Define which drives are OPUS memory volumes
$opusDrives = @(
    @{ Letter = 'E'; NodeName = 'SABRETOOTH';  Role = 'dev-orchestrator' },
    @{ Letter = 'G'; NodeName = 'T5500';       Role = 'prod-dating-app'  },
    @{ Letter = 'H'; NodeName = 'OPTIPLEX9020';Role = 'infra-legacy'     }
)

# 2. Validate drives exist, create OPUSONLY structure
$nodeEntries = @()

foreach ($d in $opusDrives) {
    $letter  = $d.Letter
    $node    = $d.NodeName
    $role    = $d.Role

    $drive = Get-PSDrive -Name $letter -ErrorAction SilentlyContinue

    if (-not $drive) {
        Write-Warning "Drive $letter`: not found. Skipping node $node."
        continue
    }

    $rootPath = "$letter`:\OPUSONLY"

    # Create base OPUSONLY folder (non-destructive)
    if (-not (Test-Path $rootPath)) {
        New-Item -ItemType Directory -Path $rootPath | Out-Null
        Write-Host "Created OPUS root: $rootPath" -ForegroundColor Green
    } else {
        Write-Host "Found OPUS root:  $rootPath" -ForegroundColor Yellow
    }

    # Create standard subfolders
    $subFolders = @(
        "$rootPath\config",
        "$rootPath\logs",
        "$rootPath\memory",
        "$rootPath\nodes",
        "$rootPath\scripts"
    )

    foreach ($sf in $subFolders) {
        if (-not (Test-Path $sf)) {
            New-Item -ItemType Directory -Path $sf | Out-Null
            Write-Host "  [+] Created: $sf"
        }
    }

    # Per-node folder on its own drive
    $nodeFolder = "$rootPath\nodes\$node"
    if (-not (Test-Path $nodeFolder)) {
        New-Item -ItemType Directory -Path $nodeFolder | Out-Null
        # IMPORTANT: avoid $node: parsing issue
        Write-Host ("  [+] Node folder for {0}: {1}" -f $node, $nodeFolder)
    }

    # Collect info for node_manifest.json (central on E:)
    $nodeEntries += [PSCustomObject]@{
        name        = $node
        role        = $role
        driveLetter = $letter
        opusRoot    = $rootPath
        nodeFolder  = $nodeFolder
    }
}

# If E: is missing, we can't write central manifest
$eDrive = Get-PSDrive -Name 'E' -ErrorAction SilentlyContinue
if (-not $eDrive) {
    Write-Warning "Drive E: not found. Cannot write central node_manifest.json."
    Write-Host "=== OPUS DRIVE SETUP COMPLETE (WITH WARNINGS) ===" -ForegroundColor Yellow
    exit 0
}

$centralConfigDir = "E:\OPUSONLY\config"
if (-not (Test-Path $centralConfigDir)) {
    New-Item -ItemType Directory -Path $centralConfigDir | Out-Null
}

$manifestPath = Join-Path $centralConfigDir "node_manifest.json"

$manifestObj = @{
    generatedOn = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
    hostMachine = $env:COMPUTERNAME
    nodes       = $nodeEntries
}

$manifestJson = $manifestObj | ConvertTo-Json -Depth 5
$manifestJson | Out-File -FilePath $manifestPath -Encoding utf8

Write-Host ""
Write-Host "Central node manifest written to:" -ForegroundColor Green
Write-Host "  $manifestPath" -ForegroundColor Green

# Optional: drop a tiny README so it's obvious what these folders are
$readmePath = "E:\OPUSONLY\README_OPUS_DRIVES.txt"
if (-not (Test-Path $readmePath)) {
    @"
OPUS Multi-Node Memory Layout
=============================

This machine (SABRETOOTH) sees three OPUS memory drives:

- SABRETOOTH local: E:\OPUSONLY
- T5500 OS disk:    G:\OPUSONLY
- 9020 OS disk:     H:\OPUSONLY

Each drive contains:
- config\   -> node manifests, project indexes, settings
- logs\     -> any future orchestration logs
- memory\   -> long-term assistant memory payloads
- nodes\    -> per-node subfolders
- scripts\  -> automation scripts

DO NOT DELETE these folders if you want persistent memory across nodes.

Generated by Setup-OpusDrives.ps1
"@ | Out-File -FilePath $readmePath -Encoding utf8
    Write-Host "README created at: $readmePath" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== OPUS DRIVE SETUP COMPLETE (E, G, H configured) ===" -ForegroundColor Cyan
