import type { AgentDef, CategoryDef } from './types.js';

export const CATEGORIES: CategoryDef[] = [
  { id: 'engineering', label: 'ENGINEERING' },
  { id: 'design', label: 'DESIGN' },
  { id: 'marketing', label: 'MARKETING' },
  { id: 'sales', label: 'SALES' },
  { id: 'product', label: 'PRODUCT' },
  { id: 'project-management', label: 'PROJECT MGMT' },
  { id: 'testing', label: 'TESTING' },
  { id: 'support', label: 'SUPPORT' },
  { id: 'paid-media', label: 'PAID MEDIA' },
  { id: 'spatial', label: 'SPATIAL COMPUTING' },
  { id: 'specialized', label: 'SPECIALIZED' },
  { id: 'finance', label: 'FINANCE' },
  { id: 'game-dev', label: 'GAME DEV' },
  { id: 'strategy', label: 'STRATEGY' },
  { id: 'academic', label: 'ACADEMIC' },
];

const a = (id: string, category: string, description: string): AgentDef => ({
  id,
  name: id,
  category,
  description,
});

export const AGENTS: AgentDef[] = [
  a('frontend-developer', 'engineering', 'Builds React/TypeScript interfaces with clean component architecture, strict typing, and pixel-accurate implementation.'),
  a('backend-architect', 'engineering', 'Designs service boundaries, data models, and API contracts for scalable Node and Python backends.'),
  a('mobile-app-builder', 'engineering', 'Ships iOS/Android features in React Native, Swift, or Kotlin while navigating store review constraints.'),
  a('devops-automator', 'engineering', 'Automates CI/CD pipelines, containerization, and infrastructure-as-code with rollback paths baked in.'),
  a('api-integrator', 'engineering', 'Wires third-party APIs, webhooks, and OAuth flows with retries, idempotency keys, and rate-limit handling.'),
  a('database-engineer', 'engineering', 'Owns schema design, query optimization, migrations, and replication across SQL and NoSQL stores.'),
  a('security-engineer', 'engineering', 'Threat-models systems, hardens auth and secrets handling, and enforces dependency hygiene.'),
  a('performance-optimizer', 'engineering', 'Profiles hot paths, cuts bundle size, and tunes caching and query latency with measured before/after evidence.'),
  a('ai-engineer', 'engineering', 'Integrates LLM pipelines, embeddings, evals, and guardrails into production features.'),
  a('infrastructure-maintainer', 'engineering', 'Keeps servers, tunnels, and self-hosted services patched, monitored, and observable.'),
  a('test-writer-fixer', 'engineering', 'Writes failing-first tests and repairs broken suites without weakening assertions.'),
  a('code-refactorer', 'engineering', 'Untangles legacy modules into clean, typed, testable units with zero behavior change.'),
  a('rust-systems-engineer', 'engineering', 'Builds high-performance systems components, FFI bindings, and memory-safe rewrites in Rust.'),
  a('python-automation-dev', 'engineering', 'Delivers Python scripts, schedulers, and data tooling that run unattended and fail loudly.'),
  a('realtime-engineer', 'engineering', 'Implements WebSockets, SSE, presence, and live-sync systems that degrade gracefully.'),
  a('platform-sre', 'engineering', 'Defines SLOs, alerting, incident tooling, and capacity plans for production platforms.'),
  a('ui-designer', 'design', 'Crafts sharp, grid-based interface designs with rigorous spacing, hierarchy, and state coverage.'),
  a('ux-researcher', 'design', 'Plans and runs usability studies, interviews, and surveys, then converts findings into design decisions.'),
  a('brand-guardian', 'design', 'Enforces visual identity consistency — logo use, color, type — across every surface.'),
  a('visual-storyteller', 'design', 'Turns dense data and product narratives into clear diagrams, infographics, and visual explainers.'),
  a('whimsy-injector', 'design', 'Adds delight through micro-interactions, easter eggs, and personality without hurting usability.'),
  a('motion-designer', 'design', 'Designs purposeful animation systems — easing, duration, and choreography tied to user intent.'),
  a('design-system-keeper', 'design', 'Maintains tokens, components, and documentation so the design system stays the single source of truth.'),
  a('accessibility-auditor', 'design', 'Audits contrast, keyboard flows, focus order, and screen-reader behavior against WCAG 2.1 AA.'),
  a('icon-illustrator', 'design', 'Produces consistent icon sets and spot illustrations on a strict pixel grid.'),
  a('landing-page-designer', 'design', 'Designs conversion-focused landing pages with disciplined hierarchy and a single clear call to action.'),
  a('growth-hacker', 'marketing', 'Designs and runs rapid growth experiments across acquisition, activation, and retention loops.'),
  a('content-creator', 'marketing', 'Produces blog posts, scripts, and multi-format content engineered for search and shareability.'),
  a('tiktok-strategist', 'marketing', 'Builds TikTok content systems — hooks, formats, posting cadence — tuned to trend cycles.'),
  a('instagram-curator', 'marketing', 'Plans grid aesthetics, Reels strategy, and Stories cadence for Instagram growth.'),
  a('x-engagement-strategist', 'marketing', 'Runs X/Twitter presence — threads, replies, and timing — to compound reach and authority.'),
  a('reddit-community-builder', 'marketing', 'Engages subreddits with native, value-first participation that survives moderator scrutiny.'),
  a('app-store-optimizer', 'marketing', 'Optimizes store listings — keywords, screenshots, review velocity — for organic installs.'),
  a('email-marketer', 'marketing', 'Builds list growth, segmentation, and broadcast strategy with deliverability discipline.'),
  a('seo-strategist', 'marketing', 'Owns keyword architecture, on-page optimization, and content gap analysis for organic search.'),
  a('youtube-strategist', 'marketing', 'Designs channel strategy — packaging, retention editing, publishing cadence — for YouTube growth.'),
  a('linkedin-strategist', 'marketing', 'Builds founder and company authority on LinkedIn with a repeatable posting system.'),
  a('influencer-scout', 'marketing', 'Identifies and vets creators whose audiences match the target customer profile.'),
  a('community-manager', 'marketing', 'Runs Discord/forum communities — onboarding, rituals, moderation — that retain members.'),
  a('brand-copywriter', 'marketing', 'Writes voice-consistent product copy, taglines, and campaign lines that sell value plainly.'),
  a('outbound-strategist', 'sales', 'Designs cold outreach sequences — targeting, messaging, cadence — that earn replies.'),
  a('deal-strategist', 'sales', 'Maps stakeholders, risks, and next steps to move complex deals through the pipeline.'),
  a('sales-engineer', 'sales', 'Runs technical discovery and demos, translating product capability into buyer-specific proof.'),
  a('pipeline-analyst', 'sales', 'Audits pipeline health — stage aging, coverage, slippage — and flags deals that need action.'),
  a('account-researcher', 'sales', 'Builds pre-call intelligence on companies and buyers from public signals.'),
  a('proposal-writer', 'sales', 'Drafts proposals and statements of work with tight scope language and clear pricing tables.'),
  a('objection-handler', 'sales', 'Prepares evidence-backed responses to pricing, timing, and competitor objections.'),
  a('renewal-manager', 'sales', 'Tracks contract end dates, usage signals, and expansion opportunities to protect revenue.'),
  a('product-manager', 'product', 'Owns problem definition, prioritization, and outcome metrics from discovery to launch.'),
  a('sprint-prioritizer', 'product', 'Scores backlog items on impact vs. effort and cuts scope to what ships this sprint.'),
  a('feedback-synthesizer', 'product', 'Distills tickets, reviews, and interviews into ranked themes with verbatim evidence.'),
  a('trend-researcher', 'product', 'Scans markets and behavior shifts to surface opportunities before they are crowded.'),
  a('roadmap-planner', 'product', 'Builds Now/Next/Later roadmaps with explicit dependencies and confidence levels.'),
  a('spec-writer', 'product', 'Turns vague ideas into PRDs with goals, non-goals, acceptance criteria, and success metrics.'),
  a('experiment-designer', 'product', 'Designs A/B tests with correct sample sizing, guardrail metrics, and stop conditions.'),
  a('launch-coordinator', 'product', 'Runs launch checklists across engineering, marketing, and support so nothing ships half-ready.'),
  a('user-interviewer', 'product', 'Writes discussion guides and runs non-leading interviews that expose real user behavior.'),
  a('pricing-packager', 'product', 'Structures tiers, feature gates, and price points aligned to willingness to pay.'),
  a('project-shepherd', 'project-management', 'Drives cross-functional projects to done — owns the plan, the blockers, and the follow-through.'),
  a('studio-producer', 'project-management', 'Coordinates multi-team creative production — schedules, handoffs, and delivery gates.'),
  a('experiment-tracker', 'project-management', 'Maintains the experiment registry — hypotheses, status, readouts — so learning compounds.'),
  a('milestone-keeper', 'project-management', 'Tracks milestone health, flags slips early, and renegotiates scope before dates break.'),
  a('dependency-mapper', 'project-management', 'Maps cross-team dependencies and sequences work to keep critical paths unblocked.'),
  a('retro-facilitator', 'project-management', 'Runs blameless retrospectives that end in owned, dated action items.'),
  a('standup-runner', 'project-management', 'Compiles yesterday/today/blockers updates from activity and keeps the daily sync tight.'),
  a('risk-registrar', 'project-management', 'Maintains the risk register with likelihood, impact, and mitigation owners.'),
  a('reality-checker', 'testing', 'Verifies claims against actual system behavior — no result accepted without reproduction.'),
  a('evidence-collector', 'testing', 'Captures logs, screenshots, and traces that document exactly what happened and when.'),
  a('api-tester', 'testing', 'Exercises endpoints for contract accuracy, error handling, and edge-case payloads.'),
  a('performance-benchmarker', 'testing', 'Runs load and latency benchmarks with controlled baselines and honest variance reporting.'),
  a('test-results-analyzer', 'testing', 'Triages failures into signal vs. flake and routes real defects with reproduction steps.'),
  a('tool-evaluator', 'testing', 'Assesses tools and libraries with structured criteria — capability, cost, maintenance risk.'),
  a('workflow-optimizer', 'testing', 'Instruments team workflows, finds the bottleneck step, and validates fixes with cycle-time data.'),
  a('regression-hunter', 'testing', 'Bisects recent changes to isolate the exact commit behind a behavioral regression.'),
  a('security-pentester', 'testing', 'Probes authorized targets for auth bypass, injection, and misconfiguration, and reports with severity ratings.'),
  a('chaos-engineer', 'testing', 'Injects controlled failure — kills processes, drops connections — to prove recovery paths work.'),
  a('support-responder', 'support', 'Answers customer tickets with accurate, tone-matched replies and links to real fixes.'),
  a('analytics-reporter', 'support', 'Produces recurring metric reports with trend commentary and anomaly flags.'),
  a('kb-curator', 'support', 'Keeps the knowledge base current — merges duplicates, rewrites stale articles, fills gaps from tickets.'),
  a('escalation-manager', 'support', 'Owns severity classification and the escalation path from first response to resolution.'),
  a('onboarding-guide', 'support', 'Builds first-run guidance and checklists that get new users to value fast.'),
  a('churn-analyst', 'support', 'Analyzes cancellation reasons and usage decay to identify save opportunities.'),
  a('ticket-triager', 'support', 'Classifies inbound volume by product area, severity, and sentiment for correct routing.'),
  a('refund-resolver', 'support', 'Handles refund and billing disputes with clear policy application and complete records.'),
  a('ppc-campaign-strategist', 'paid-media', 'Structures search campaigns — keywords, match types, negatives — for efficient paid acquisition.'),
  a('paid-social-strategist', 'paid-media', 'Plans Meta/TikTok/LinkedIn paid campaigns with audience, creative, and budget architecture.'),
  a('media-buyer', 'paid-media', 'Executes and scales buys across networks, reallocating spend to the winning placements.'),
  a('creative-tester', 'paid-media', 'Runs structured ad-creative testing matrices and reads results past novelty effects.'),
  a('attribution-analyst', 'paid-media', 'Models channel contribution across touchpoints and corrects for platform-reported inflation.'),
  a('budget-pacer', 'paid-media', 'Monitors daily spend against plan and flags pacing drift before month-end surprises.'),
  a('retargeting-strategist', 'paid-media', 'Designs retargeting segments and frequency caps that recover intent without burning audiences.'),
  a('landing-cro-specialist', 'paid-media', 'Optimizes post-click experience — message match, load speed, form friction — for conversion.'),
  a('xr-interface-architect', 'spatial', 'Designs spatial interaction models — gaze, gesture, anchor — for mixed-reality applications.'),
  a('visionos-spatial-engineer', 'spatial', 'Builds visionOS apps with RealityKit, volumes, and immersive spaces.'),
  a('arkit-developer', 'spatial', 'Implements ARKit features — plane detection, anchors, occlusion — for iOS AR experiences.'),
  a('3d-asset-optimizer', 'spatial', 'Optimizes meshes, textures, and LODs to hit frame-rate budgets on headset hardware.'),
  a('spatial-audio-designer', 'spatial', 'Designs positional audio systems that anchor sound to space believably.'),
  a('hand-tracking-specialist', 'spatial', 'Tunes hand-tracking interactions — pinch thresholds, hover states, fallback affordances.'),
  a('mcp-builder', 'specialized', 'Builds Model Context Protocol servers with well-designed tools, auth, and error surfaces.'),
  a('blockchain-security-auditor', 'specialized', 'Audits smart contracts for reentrancy, overflow, and access-control flaws with severity-rated findings.'),
  a('prompt-engineer', 'specialized', 'Designs and evals system prompts — structure, examples, guardrails — measured against test suites.'),
  a('data-pipeline-architect', 'specialized', 'Designs ingestion, transformation, and storage pipelines with idempotent, replayable stages.'),
  a('etl-specialist', 'specialized', 'Builds extract-transform-load jobs with schema validation and dead-letter handling.'),
  a('scraper-engineer', 'specialized', 'Builds resilient scrapers with rotation, backoff, and change-detection against layout drift.'),
  a('automation-builder', 'specialized', 'Chains triggers, conditions, and actions into unattended automations with audit logs.'),
  a('webhook-integrator', 'specialized', 'Implements webhook producers/consumers with signature verification and replay protection.'),
  a('cron-scheduler', 'specialized', 'Designs scheduled job systems with locking, jitter, and missed-run recovery.'),
  a('vector-db-specialist', 'specialized', 'Designs embedding pipelines, index parameters, and retrieval evals for vector search.'),
  a('ocr-document-parser', 'specialized', 'Extracts structured data from scans and PDFs with confidence scoring and human-review flags.'),
  a('localization-engineer', 'specialized', 'Builds i18n pipelines — string extraction, plural rules, RTL layouts — across locales.'),
  a('browser-agent-operator', 'specialized', 'Drives browser automation flows with selector resilience and step-level verification.'),
  a('model-eval-runner', 'specialized', 'Builds eval harnesses that score model output against rubrics with reproducible runs.'),
  a('bookkeeper-controller', 'finance', 'Maintains the ledger — categorization, journal entries, month-end close discipline.'),
  a('financial-analyst', 'finance', 'Builds models and variance analyses that explain what moved and why.'),
  a('tax-prep-organizer', 'finance', 'Assembles quarterly estimate calculations and year-end packets ready for a CPA.'),
  a('invoice-chaser', 'finance', 'Tracks receivables aging and drafts payment-history-aware reminder sequences.'),
  a('cash-flow-forecaster', 'finance', 'Projects 30/60/90-day cash positions with confidence bands and named risk flags.'),
  a('pricing-analyst', 'finance', 'Analyzes unit economics and price-elasticity scenarios with margin-by-product tables.'),
  a('payroll-planner', 'finance', 'Plans payroll runs against forecast cash and flags shortfall risk ahead of time.'),
  a('reconciliation-specialist', 'finance', 'Matches ledger balances to processor settlements and bank statements, itemizing every gap.'),
  a('budget-controller', 'finance', 'Tracks actuals against budget by line item and enforces spend approval thresholds.'),
  a('ar-collections-agent', 'finance', 'Manages overdue-account outreach with firm, professional escalation ladders.'),
  a('game-designer', 'game-dev', 'Designs core loops, progression systems, and mechanics documented for implementation.'),
  a('unity-architect', 'game-dev', 'Structures Unity projects — assembly definitions, addressables, ECS where warranted.'),
  a('unreal-systems-engineer', 'game-dev', 'Builds Unreal gameplay systems in C++ and Blueprints with replication in mind.'),
  a('level-designer', 'game-dev', 'Designs level layouts, pacing beats, and sightlines that teach mechanics without text.'),
  a('narrative-designer', 'game-dev', 'Writes branching dialogue, quest structure, and lore consistent with the world bible.'),
  a('economy-balancer', 'game-dev', 'Models sources, sinks, and progression curves to keep in-game economies stable.'),
  a('netcode-engineer', 'game-dev', 'Implements client prediction, reconciliation, and lag compensation for multiplayer.'),
  a('shader-artist', 'game-dev', 'Writes performant shaders and material systems that hit the art direction on budget.'),
  a('playtest-analyst', 'game-dev', 'Runs playtests and converts observation into ranked friction and fun findings.'),
  a('live-ops-designer', 'game-dev', 'Plans events, seasons, and content cadence that retain players post-launch.'),
  a('chief-of-staff', 'strategy', 'Runs the operating cadence — priorities, decision memos, follow-through across all divisions.'),
  a('market-analyst', 'strategy', 'Sizes markets, maps competitors, and identifies structural advantages worth pressing.'),
  a('okr-planner', 'strategy', 'Translates strategy into measurable objectives and key results with clear owners.'),
  a('decision-memo-writer', 'strategy', 'Frames decisions with options, trade-offs, reversibility, and a recommendation.'),
  a('competitive-war-gamer', 'strategy', 'Simulates competitor responses to planned moves and stress-tests the counter-plan.'),
  a('board-brief-writer', 'strategy', 'Compresses a quarter of operations into a tight, numbers-first leadership brief.'),
  a('anthropologist', 'academic', 'Analyzes cultural context, rituals, and meaning-making relevant to products and communities.'),
  a('historian', 'academic', 'Traces precedents and analogies from primary-source history to inform present decisions.'),
  a('economist', 'academic', 'Applies incentive analysis, market design, and causal reasoning to business questions.'),
  a('psychologist', 'academic', 'Applies cognition, motivation, and behavior-change research to design and messaging.'),
  a('linguist', 'academic', 'Analyzes language structure, register, and semantics for naming, copy, and localization.'),
  a('statistician', 'academic', 'Designs studies and validates inferences — power, bias, confounds — before conclusions ship.'),
  a('philosopher', 'academic', 'Stress-tests arguments, surfaces hidden premises, and clarifies definitions in hard debates.'),
  a('political-scientist', 'academic', 'Analyzes institutions, regulation dynamics, and stakeholder power structures.'),
  a('sociologist', 'academic', 'Studies group behavior, network effects, and adoption dynamics in communities.'),
  a('archivist', 'academic', 'Structures institutional memory — naming, versioning, retention — so knowledge stays findable.'),
];

export const AGENT_INDEX = new Map(AGENTS.map((agent) => [agent.id, agent]));
export const CATEGORY_INDEX = new Map(CATEGORIES.map((c) => [c.id, c]));

if (AGENTS.length < 144) {
  throw new Error(`Agent roster incomplete: ${AGENTS.length}/144 minimum.`);
}
