import React, { useState } from 'react';
import { Share2, Lock, Github, Cloud, PenSquare, ArrowRight, Rss, CloudRain, Activity, Map, Ticket, Calendar, TrendingUp, Users } from 'lucide-react';
import { motion } from 'framer-motion';

export function SocialCommandCenter() {
  const [activeTab, setActiveTab] = useState<'publish' | 'logins' | 'repo' | 'analytics' | 'roadmap'>('publish');
  
  const [postContent, setPostContent] = useState('');
  const [postType, setPostType] = useState('feed');
  const [isPublishing, setIsPublishing] = useState(false);

  // Example functionality for Repo pull
  const handlePullRepo = async () => {
    if (window.opuspawclaw) {
      try {
        await window.opuspawclaw.terminalExec(`git clone https://github.com/Trollz1004/Antigravity.git ./Antigravity`);
        alert("Pulling Trollz1004/Antigravity into active workspace...");
      } catch (e) {
        console.error(e);
      }
    }
  };

  return (
    <div className="flex flex-col h-full bg-[#0a0f1a] text-[#e8f0ff] p-8 overflow-y-auto custom-scrollbar">
      <div className="max-w-5xl w-full mx-auto">
        <div className="flex items-center gap-4 mb-8">
          <div className="p-3 bg-[#111827] border border-[#2a3a52] rounded-xl shadow-[0_0_20px_rgba(224,64,251,0.15)]">
            <Share2 size={28} className="text-[#e040fb]" />
          </div>
          <div>
            <h2 className="text-3xl font-black uppercase tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-[#00d4ff] to-[#e040fb]">
              Social Command Center
            </h2>
            <p className="text-[#6b82a6] font-medium text-xs mt-1">
              Opus & Gemini Marketing Dispatch • DAO Portal Integrations
            </p>
          </div>
        </div>

        <div className="flex gap-4 mb-6 border-b border-[#2a3a52] overflow-x-auto hide-scrollbar pb-1">
          {['publish', 'logins', 'repo', 'analytics', 'roadmap'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab as any)}
              className={`px-4 py-2 text-[11px] font-bold uppercase tracking-widest border-b-2 transition-colors whitespace-nowrap ${
                activeTab === tab 
                  ? 'border-[#00d4ff] text-[#00d4ff]' 
                  : 'border-transparent text-[#6b82a6] hover:text-[#e8f0ff]'
              }`}
            >
              {tab === 'publish' ? 'Dispatch Content' : 
               tab === 'logins' ? 'Auth & Logins' : 
               tab === 'repo' ? 'AI Team Ops' : 
               tab === 'analytics' ? 'App Analytics' : 'DAO Roadmap'}
            </button>
          ))}
        </div>

        {activeTab === 'publish' && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl relative overflow-hidden group">
              <div className="absolute -right-10 -top-10 opacity-5 group-hover:opacity-10 transition-opacity">
                <PenSquare size={200} className="text-[#e040fb]" />
              </div>
              <div className="relative z-10 flex flex-col h-full">
                <h3 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-widest mb-4 flex items-center gap-2">
                  <CloudRain size={16} className="text-[#00d4ff]" /> Compose Broadcast
                </h3>
                <textarea
                  value={postContent}
                  onChange={e => setPostContent(e.target.value)}
                  placeholder="Paste marketing copy generated by Gemini or Perplexity here..."
                  className="flex-1 min-h-[250px] w-full bg-[#0a0f1a] border border-[#2a3a52] rounded-lg p-4 text-sm text-[#e8f0ff] focus:border-[#e040fb] focus:ring-1 focus:ring-[#e040fb]/20 outline-none resize-none mb-4 custom-scrollbar"
                />
                
                <div className="flex items-center gap-4 mb-4">
                  <label className="text-[10px] font-bold text-[#6b82a6] uppercase tracking-wider">Target Format:</label>
                  <select 
                    value={postType}
                    onChange={e => setPostType(e.target.value)}
                    className="bg-[#0a0f1a] border border-[#2a3a52] rounded px-3 py-1.5 text-xs focus:border-[#e040fb] outline-none text-[#e8f0ff]"
                  >
                    <option value="feed">Main Feed (X/LinkedIn)</option>
                    <option value="thread">Thread / Markdown</option>
                    <option value="story">Ephemeral Story</option>
                    <option value="blog">AI Blog Post (Hugo/Ghost)</option>
                  </select>
                </div>

                <div className="bg-[#00d4ff]/10 border border-[#00d4ff]/20 p-3 rounded-lg mb-4 flex items-start gap-3">
                  <Rss size={16} className="text-[#00d4ff] mt-0.5" />
                  <div>
                    <span className="block text-[10px] font-bold text-[#00d4ff] uppercase tracking-wider mb-1">AI Solutions Blog Integration</span>
                    <a href="https://blog.ai-solutions.store" target="_blank" rel="noreferrer" className="text-xs text-[#e8f0ff] hover:underline">
                      blog.ai-solutions.store
                    </a>
                  </div>
                </div>

                <button 
                  onClick={() => {
                    setIsPublishing(true);
                    setTimeout(() => { setIsPublishing(false); setPostContent(''); }, 1500);
                  }}
                  disabled={isPublishing || !postContent}
                  className="w-full bg-gradient-to-r from-[#e040fb] to-[#9c27b0] hover:shadow-[0_0_20px_rgba(224,64,251,0.4)] disabled:opacity-50 text-white font-black uppercase tracking-[0.2em] py-3 rounded-lg transition-all active:scale-[0.98] flex items-center justify-center gap-2"
                >
                  {isPublishing ? 'Transmitting...' : 'Initiate Dispatch'}
                  <ArrowRight size={16} className={isPublishing ? 'animate-ping' : ''} />
                </button>
              </div>
            </div>

            <div className="space-y-4">
              {/* Output Preview / Config Side */}
              <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl">
                <h3 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-widest mb-4">Payload Preview</h3>
                <div className="bg-[#0a0f1a] p-4 rounded-lg border border-[#2a3a52] min-h-[150px] whitespace-pre-wrap text-sm text-[#a0aec0]">
                  {postContent || "Preview content will appear here..."}
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'logins' && (
          <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl max-w-2xl">
            <h3 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-widest mb-6 flex items-center gap-2">
              <Lock size={16} className="text-[#e040fb]" /> Platform Authentication Vault (Local)
            </h3>
            
            <div className="space-y-4">
              {[
                { platform: 'Twitter / X API', status: 'connected' },
                { platform: 'LinkedIn Dev API', status: 'disconnected' },
                { platform: 'Ghost Blog Admin', status: 'connected' },
                { platform: 'Instagram Graph', status: 'disconnected' }
              ].map(app => (
                <div key={app.platform} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 bg-[#0a0f1a] border border-[#2a3a52] rounded-lg">
                  <div className="flex items-center gap-3 mb-2 sm:mb-0">
                    <div className={`w-2 h-2 rounded-full ${app.status === 'connected' ? 'bg-[#00e676] shadow-[0_0_8px_#00e676]' : 'bg-[#4a5568]'}`} />
                    <span className="font-medium text-sm text-[#e8f0ff]">{app.platform}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <input 
                      type="password" 
                      placeholder="Bearer / App Key" 
                      className="bg-[#111827] border border-[#2a3a52] rounded px-3 py-1.5 text-xs text-[#e8f0ff] w-full sm:w-48 outline-none focus:border-[#e040fb]" 
                    />
                    <button className="px-3 py-1.5 bg-[#1a2332] hover:bg-[#2a3a52] text-[10px] font-bold uppercase tracking-widest text-[#00d4ff] rounded transition-colors whitespace-nowrap">
                      Save
                    </button>
                  </div>
                </div>
              ))}
            </div>
            <p className="mt-4 text-[10px] text-[#6b82a6] italic">Note: These credentials are saved to local ApplicationData storage, not synched remotely, preserving isolation.</p>
          </div>
        )}

        {activeTab === 'repo' && (
          <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl max-w-2xl">
             <h3 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-widest mb-6 flex items-center gap-2">
              <Github size={16} className="text-[#00e676]" /> Core AI Team CLI Ops
            </h3>

            <div className="bg-[#0a0f1a] border border-[#2ae676]/30 p-4 rounded-xl mb-6 flex items-start gap-3">
              <Lock size={16} className="text-[#00e676] mt-0.5" />
              <div>
                <span className="block text-[11px] font-bold text-[#00e676] uppercase tracking-wider mb-1">CLI Auth Protocol Active</span>
                <p className="text-xs text-[#a0aec0] mb-2 leading-relaxed">
                  Authentication gateway integrated for Trollz1004. Terminal interface is mapped securely. Compatible with Claude.ai remote dispatch and Jules.py local executable.
                </p>
                <div className="flex gap-2">
                  <span className="px-2 py-0.5 bg-[#00e676]/10 text-[#00e676] rounded text-[9px] uppercase font-bold border border-[#00e676]/20">User: Trollz1004</span>
                  <span className="px-2 py-0.5 bg-[#e040fb]/10 text-[#e040fb] rounded text-[9px] uppercase font-bold border border-[#e040fb]/20">Opus/Gemini Ready</span>
                </div>
              </div>
            </div>

            <div className="p-5 border border-[#2a3a52] bg-[#1a2332] rounded-lg mb-4">
               <h4 className="text-[10px] uppercase font-bold text-[#6b82a6] tracking-widest mb-3">Antigravity Source Bridge</h4>
               <p className="text-xs text-[#e8f0ff] mb-4">Initialize the flagship Antigravity CLI repository locally to synchronize changes across the fleet.</p>
               <button 
                onClick={handlePullRepo}
                className="w-full bg-[#00e676]/10 hover:bg-[#00e676]/20 text-[#00e676] border border-[#00e676]/30 font-bold uppercase tracking-widest py-3 rounded-lg transition-all active:scale-[0.98] flex items-center justify-center gap-2 text-[11px]"
               >
                 <Cloud size={14} /> Pull Trollz1004/Antigravity
               </button>
            </div>
          </div>
        )}

        {activeTab === 'analytics' && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl">
                <div className="flex items-center gap-3 text-[#00d4ff] mb-2">
                  <Users size={20} />
                  <h4 className="text-[10px] font-bold uppercase tracking-widest">Active Users (Date App)</h4>
                </div>
                <div className="text-3xl font-black text-[#e8f0ff] mt-2">12,458</div>
                <div className="text-xs text-[#00e676] mt-2 flex items-center gap-1"><TrendingUp size={12} /> +14.2% this week</div>
              </div>
              <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl">
                <div className="flex items-center gap-3 text-[#e040fb] mb-2">
                  <Activity size={20} />
                  <h4 className="text-[10px] font-bold uppercase tracking-widest">Match Rate</h4>
                </div>
                <div className="text-3xl font-black text-[#e8f0ff] mt-2">68.4%</div>
                <div className="text-xs text-[#e040fb] mt-2 flex items-center gap-1">+2.1% from AI matches</div>
              </div>
              <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl">
                <div className="flex items-center gap-3 text-[#00e676] mb-2">
                  <TrendingUp size={20} />
                  <h4 className="text-[10px] font-bold uppercase tracking-widest">Revenue Impact</h4>
                </div>
                <div className="text-3xl font-black text-[#e8f0ff] mt-2">$4,290</div>
                <div className="text-xs text-[#6b82a6] mt-2">Estimated MRR Boost</div>
              </div>
            </div>

            <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl w-full h-[300px] flex items-center justify-center">
              <div className="text-center">
                <Activity size={48} className="text-[#2a3a52] mx-auto mb-4" />
                <p className="text-sm text-[#6b82a6] uppercase tracking-widest font-bold">Chart Integration Pending...</p>
                <p className="text-[10px] text-[#4a5568] mt-2">Awaiting Recharts/D3 injection</p>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'roadmap' && (
          <div className="bg-[#111827] rounded-xl border border-[#2a3a52] p-6 shadow-xl max-w-4xl">
             <h3 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-widest mb-6 flex items-center gap-2">
              <Map size={16} className="text-[#ff3d00]" /> Multi-DAO Launch & Integration Roadmap
            </h3>

            <div className="space-y-6">
              <div className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[#00e676]/20 border border-[#00e676] flex items-center justify-center text-[#00e676] font-bold text-xs mt-1">1</div>
                  <div className="flex-1 w-px bg-[#2a3a52] my-2"></div>
                </div>
                <div className="bg-[#0a0f1a] border border-[#2a3a52] p-4 rounded-xl flex-1 mb-4 border-l-4 border-l-[#00e676]">
                  <h4 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-wider mb-1">Phase 1: Date App Finalization (Target: Friday)</h4>
                  <p className="text-xs text-[#a0aec0] mb-2 leading-relaxed">
                    Complete transition and QA of the Date App. Enable the local models (Mistral/Llama3) to refine matching algorithms. Prep for Opus deployment across active branches. Assure multi-auth functionality is intact.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[#e040fb]/20 border border-[#e040fb] flex items-center justify-center text-[#e040fb] font-bold text-xs mt-1">2</div>
                  <div className="flex-1 w-px bg-[#2a3a52] my-2"></div>
                </div>
                <div className="bg-[#0a0f1a] border border-[#2a3a52] p-4 rounded-xl flex-1 mb-4 border-l-4 border-l-[#e040fb]">
                  <h4 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-wider mb-1">Phase 2: Multi-DAO Synthesis (Target: Next Tuesday)</h4>
                  <p className="text-xs text-[#a0aec0] mb-2 leading-relaxed">
                    Once Date App is sold and finalized, transition full compute to DAO integration. Sync all connected DAOs to the central data stream. Validate AI agents autonomously executing smart contracts and Treasury votes.
                  </p>
                  <span className="inline-block px-2 py-1 bg-[#e040fb]/10 text-[#e040fb] text-[10px] uppercase font-bold rounded">Critical Milestone</span>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-[#00d4ff]/20 border border-[#00d4ff] flex items-center justify-center text-[#00d4ff] font-bold text-xs mt-1">3</div>
                </div>
                <div className="bg-[#0a0f1a] border border-[#2a3a52] border-dashed p-4 rounded-xl flex-1 border-l-4 border-l-[#00d4ff]">
                  <h4 className="text-sm font-bold text-[#e8f0ff] uppercase tracking-wider mb-1">Phase 3: The Opus & Gemini Convergence (Target: Mid-Next Month)</h4>
                  <p className="text-xs text-[#a0aec0] mb-2 leading-relaxed">
                    Scale operations. Deploy the Social Command Center fully autonomous, routing Opus/Gemini intelligence across social feeds simultaneously representing the DAO cluster. Antigravity system fully live.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
