/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMissionTreasury,
  IMissionTreasuryInterface,
} from "../../../src/DeadManSwitch.sol/IMissionTreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "certificateHash",
        type: "bytes32",
      },
    ],
    name: "activateStateB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMissionTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IMissionTreasuryInterface {
    return new Interface(_abi) as IMissionTreasuryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMissionTreasury {
    return new Contract(address, _abi, runner) as unknown as IMissionTreasury;
  }
}
