/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MissionTreasury {
  export type DisbursementStruct = {
    recipient: AddressLike;
    amount: BigNumberish;
    bucketId: string;
    purpose: string;
    timestamp: BigNumberish;
  };

  export type DisbursementStructOutput = [
    recipient: string,
    amount: bigint,
    bucketId: string,
    purpose: string,
    timestamp: bigint
  ] & {
    recipient: string;
    amount: bigint;
    bucketId: string;
    purpose: string;
    timestamp: bigint;
  };
}

export interface MissionTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "activateStateB"
      | "approveRecipient"
      | "approvedRecipients"
      | "bucketDisbursed"
      | "bucketReceived"
      | "deadManSwitch"
      | "disburse"
      | "disbursementCount"
      | "disbursements"
      | "getDisbursement"
      | "gnosisSafe"
      | "isApproved"
      | "owner"
      | "recordDeposit"
      | "renounceOwnership"
      | "revokeRecipient"
      | "stateBActive"
      | "totalBalance"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Disbursed"
      | "FundsReceived"
      | "OwnershipTransferred"
      | "RecipientApproved"
      | "RecipientRevoked"
      | "StateBActivated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activateStateB",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRecipient",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedRecipients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bucketDisbursed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "bucketReceived",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deadManSwitch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disburse",
    values: [AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disbursementCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disbursements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisbursement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisSafe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDeposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stateBActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activateStateB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bucketDisbursed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bucketReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deadManSwitch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disburse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disbursementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disbursements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisbursement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gnosisSafe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateBActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DisbursedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    bucketId: string,
    purpose: string
  ];
  export type OutputTuple = [
    recipient: string,
    amount: bigint,
    bucketId: string,
    purpose: string
  ];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    bucketId: string;
    purpose: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReceivedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    bucketId: string
  ];
  export type OutputTuple = [from: string, amount: bigint, bucketId: string];
  export interface OutputObject {
    from: string;
    amount: bigint;
    bucketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientApprovedEvent {
  export type InputTuple = [recipient: AddressLike, name: string];
  export type OutputTuple = [recipient: string, name: string];
  export interface OutputObject {
    recipient: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientRevokedEvent {
  export type InputTuple = [recipient: AddressLike];
  export type OutputTuple = [recipient: string];
  export interface OutputObject {
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateBActivatedEvent {
  export type InputTuple = [
    certificateHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [certificateHash: string, timestamp: bigint];
  export interface OutputObject {
    certificateHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MissionTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): MissionTreasury;
  waitForDeployment(): Promise<this>;

  interface: MissionTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  activateStateB: TypedContractMethod<
    [certificateHash: BytesLike],
    [void],
    "nonpayable"
  >;

  approveRecipient: TypedContractMethod<
    [recipient: AddressLike, name: string],
    [void],
    "nonpayable"
  >;

  approvedRecipients: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  bucketDisbursed: TypedContractMethod<[arg0: string], [bigint], "view">;

  bucketReceived: TypedContractMethod<[arg0: string], [bigint], "view">;

  deadManSwitch: TypedContractMethod<[], [string], "view">;

  disburse: TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      bucketId: string,
      purpose: string
    ],
    [void],
    "nonpayable"
  >;

  disbursementCount: TypedContractMethod<[], [bigint], "view">;

  disbursements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        recipient: string;
        amount: bigint;
        bucketId: string;
        purpose: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDisbursement: TypedContractMethod<
    [index: BigNumberish],
    [MissionTreasury.DisbursementStructOutput],
    "view"
  >;

  gnosisSafe: TypedContractMethod<[], [string], "view">;

  isApproved: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordDeposit: TypedContractMethod<
    [amount: BigNumberish, bucketId: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeRecipient: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  stateBActive: TypedContractMethod<[], [boolean], "view">;

  totalBalance: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activateStateB"
  ): TypedContractMethod<[certificateHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveRecipient"
  ): TypedContractMethod<
    [recipient: AddressLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedRecipients"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "bucketDisbursed"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "bucketReceived"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "deadManSwitch"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disburse"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      bucketId: string,
      purpose: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disbursementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disbursements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        recipient: string;
        amount: bigint;
        bucketId: string;
        purpose: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisbursement"
  ): TypedContractMethod<
    [index: BigNumberish],
    [MissionTreasury.DisbursementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "gnosisSafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isApproved"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDeposit"
  ): TypedContractMethod<
    [amount: BigNumberish, bucketId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRecipient"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stateBActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Disbursed"
  ): TypedContractEvent<
    DisbursedEvent.InputTuple,
    DisbursedEvent.OutputTuple,
    DisbursedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReceived"
  ): TypedContractEvent<
    FundsReceivedEvent.InputTuple,
    FundsReceivedEvent.OutputTuple,
    FundsReceivedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecipientApproved"
  ): TypedContractEvent<
    RecipientApprovedEvent.InputTuple,
    RecipientApprovedEvent.OutputTuple,
    RecipientApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RecipientRevoked"
  ): TypedContractEvent<
    RecipientRevokedEvent.InputTuple,
    RecipientRevokedEvent.OutputTuple,
    RecipientRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StateBActivated"
  ): TypedContractEvent<
    StateBActivatedEvent.InputTuple,
    StateBActivatedEvent.OutputTuple,
    StateBActivatedEvent.OutputObject
  >;

  filters: {
    "Disbursed(address,uint256,string,string)": TypedContractEvent<
      DisbursedEvent.InputTuple,
      DisbursedEvent.OutputTuple,
      DisbursedEvent.OutputObject
    >;
    Disbursed: TypedContractEvent<
      DisbursedEvent.InputTuple,
      DisbursedEvent.OutputTuple,
      DisbursedEvent.OutputObject
    >;

    "FundsReceived(address,uint256,string)": TypedContractEvent<
      FundsReceivedEvent.InputTuple,
      FundsReceivedEvent.OutputTuple,
      FundsReceivedEvent.OutputObject
    >;
    FundsReceived: TypedContractEvent<
      FundsReceivedEvent.InputTuple,
      FundsReceivedEvent.OutputTuple,
      FundsReceivedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecipientApproved(address,string)": TypedContractEvent<
      RecipientApprovedEvent.InputTuple,
      RecipientApprovedEvent.OutputTuple,
      RecipientApprovedEvent.OutputObject
    >;
    RecipientApproved: TypedContractEvent<
      RecipientApprovedEvent.InputTuple,
      RecipientApprovedEvent.OutputTuple,
      RecipientApprovedEvent.OutputObject
    >;

    "RecipientRevoked(address)": TypedContractEvent<
      RecipientRevokedEvent.InputTuple,
      RecipientRevokedEvent.OutputTuple,
      RecipientRevokedEvent.OutputObject
    >;
    RecipientRevoked: TypedContractEvent<
      RecipientRevokedEvent.InputTuple,
      RecipientRevokedEvent.OutputTuple,
      RecipientRevokedEvent.OutputObject
    >;

    "StateBActivated(bytes32,uint256)": TypedContractEvent<
      StateBActivatedEvent.InputTuple,
      StateBActivatedEvent.OutputTuple,
      StateBActivatedEvent.OutputObject
    >;
    StateBActivated: TypedContractEvent<
      StateBActivatedEvent.InputTuple,
      StateBActivatedEvent.OutputTuple,
      StateBActivatedEvent.OutputObject
    >;
  };
}
