/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PlatformSplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MISSION_BPS"
      | "OPS_BPS"
      | "TAX_BPS"
      | "TOTAL_BPS"
      | "USDC"
      | "daoId"
      | "daoTreasury"
      | "deposit"
      | "depositToken"
      | "missionPending"
      | "missionReserve"
      | "opsPending"
      | "pendingUSDC"
      | "previewSplit"
      | "taxPending"
      | "taxWallet"
      | "totalProcessed"
      | "withdrawMission"
      | "withdrawOps"
      | "withdrawTax"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Deposited" | "Withdrawn"): EventFragment;

  encodeFunctionData(
    functionFragment: "MISSION_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "OPS_BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "TAX_BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "TOTAL_BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "daoId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "missionPending",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "missionReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "opsPending",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taxPending",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "taxWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalProcessed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMission",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTax",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MISSION_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OPS_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TAX_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOTAL_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "daoId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "missionPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "missionReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "opsPending", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taxPending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taxWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTax",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    daoId: BytesLike
  ];
  export type OutputTuple = [token: string, amount: bigint, daoId: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    daoId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [recipient: string, token: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlatformSplitter extends BaseContract {
  connect(runner?: ContractRunner | null): PlatformSplitter;
  waitForDeployment(): Promise<this>;

  interface: PlatformSplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MISSION_BPS: TypedContractMethod<[], [bigint], "view">;

  OPS_BPS: TypedContractMethod<[], [bigint], "view">;

  TAX_BPS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_BPS: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  daoId: TypedContractMethod<[], [string], "view">;

  daoTreasury: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[], [void], "nonpayable">;

  depositToken: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  missionPending: TypedContractMethod<[], [bigint], "view">;

  missionReserve: TypedContractMethod<[], [string], "view">;

  opsPending: TypedContractMethod<[], [bigint], "view">;

  pendingUSDC: TypedContractMethod<[], [bigint], "view">;

  previewSplit: TypedContractMethod<
    [amount: BigNumberish],
    [[bigint, bigint, bigint] & { mission: bigint; tax: bigint; ops: bigint }],
    "view"
  >;

  taxPending: TypedContractMethod<[], [bigint], "view">;

  taxWallet: TypedContractMethod<[], [string], "view">;

  totalProcessed: TypedContractMethod<[], [bigint], "view">;

  withdrawMission: TypedContractMethod<[], [void], "nonpayable">;

  withdrawOps: TypedContractMethod<[], [void], "nonpayable">;

  withdrawTax: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MISSION_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPS_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TAX_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "daoId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "daoTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "missionPending"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "missionReserve"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "opsPending"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingUSDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewSplit"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [[bigint, bigint, bigint] & { mission: bigint; tax: bigint; ops: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "taxPending"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "taxWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalProcessed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawMission"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawOps"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawTax"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256,bytes32)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
