import { openDb } from './db.js';
import { refill_task_pool } from './task-pool.js';
import type { TaskFactoryTemplate } from './tools/task-factory.js';

function envInt(name: string, fallback: number): number {
  const raw = process.env[name];
  if (raw === undefined || raw.trim() === '') return fallback;
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isInteger(parsed) || parsed < 0) {
    throw new Error(`${name} must be a non-negative integer`);
  }
  return parsed;
}

function buildTemplate(): TaskFactoryTemplate {
  return {
    seed: process.env.TASK_POOL_TEMPLATE_SEED ?? 'mission-pool-cron',
    titlePattern: process.env.TASK_POOL_TITLE_PATTERN ?? 'Mission pool task {{paddedIndex}}/{{count}} - {{topic}}',
    body:
      process.env.TASK_POOL_BODY_PATTERN ?? 'Generated by mission-mcp pool refill batch {{batchNumber}} for {{topic}}.',
    assigned_agent_id: process.env.TASK_POOL_ASSIGNEE ?? 'ceo',
    assignee: process.env.TASK_POOL_ASSIGNEE ?? 'ceo',
    variables: {
      topic: process.env.TASK_POOL_TOPIC ?? 'mission-control',
    },
  };
}

const db = openDb();

try {
  const result = refill_task_pool(db, {
    template: buildTemplate(),
    threshold: envInt('TASK_POOL_REFILL_THRESHOLD', 20),
    target: envInt('TASK_POOL_TARGET', 100),
    maxBelowMs: envInt('TASK_POOL_MAX_BELOW_MS', 5 * 60 * 1000),
    belowSinceMs:
      process.env.TASK_POOL_BELOW_SINCE_MS === undefined ? undefined : envInt('TASK_POOL_BELOW_SINCE_MS', 0),
  });

  process.stdout.write(`${JSON.stringify(result.log)}\n`);
  if (result.alert) {
    process.stderr.write(`[mission-mcp] CRITICAL ${JSON.stringify(result.alert)}\n`);
    process.exitCode = 2;
  }
} finally {
  db.close();
}
