import { OperationsPage } from "@/components/OperationsPage";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowDownToLine, Loader2, PackageCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { FormEvent, useState } from "react";

export default function Inventory() {
  const utils = trpc.useUtils();
  const inventory = trpc.inventory.list.useQuery();
  const [productId, setProductId] = useState<number | "">("");
  const [movementType, setMovementType] = useState<"receive" | "reserve" | "release" | "sale">("receive");
  const [quantity, setQuantity] = useState(1);
  const move = trpc.inventory.move.useMutation({ onSuccess: () => { utils.inventory.list.invalidate(); utils.operations.overview.invalidate(); } });
  const submit = (event: FormEvent) => { event.preventDefault(); if (productId) move.mutate({ productId, movementType, quantity }); };
  return <OperationsPage eyebrow="Inventory ledger" title="Inventory control" description="Track on-hand, reserved, and available quantity with atomic movement checks that block overselling and log every outcome.">
    <section className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><form onSubmit={submit} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><ArrowDownToLine className="h-5 w-5 text-primary"/><h2 className="text-lg font-semibold">Ledger action</h2></div><p className="mt-1 text-sm leading-6 text-muted-foreground">A reservation or sale is blocked whenever it would make available quantity negative.</p><div className="mt-5 grid gap-3"><select required value={productId} onChange={event => setProductId(event.target.value ? Number(event.target.value) : "")} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="">Select a catalog product</option>{(inventory.data ?? []).map(item => <option key={item.productId} value={item.productId}>{item.sku} — {item.title}</option>)}</select><select value={movementType} onChange={event => setMovementType(event.target.value as typeof movementType)} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="receive">Receive on-hand quantity</option><option value="reserve">Reserve for approved work</option><option value="release">Release reservation</option><option value="sale">Commit reserved sale</option></select><input type="number" min="1" max="10000" value={quantity} onChange={event => setQuantity(Number(event.target.value))} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"/><Button disabled={!productId || move.isPending} className="gap-2">{move.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <PackageCheck className="h-4 w-4"/>} Apply ledger action</Button>{move.error ? <p className="text-sm leading-6 text-destructive">{move.error.message}</p> : null}</div></form><div className="rounded-2xl bg-slate-950 p-6 text-slate-50 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Availability formula</p><p className="mt-6 text-3xl font-semibold tracking-tight">On-hand − reserved</p><p className="mt-3 max-w-md text-sm leading-6 text-slate-300">Available quantity is calculated before a reservation or sale is applied. Blocked actions create an exception and an activity-ledger entry.</p><Badge className="mt-6 bg-teal-300/15 text-teal-100 hover:bg-teal-300/15">Atomic update checks</Badge></div></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Current availability</h2><p className="mt-1 text-sm text-muted-foreground">Only product records with an inventory ledger entry appear here.</p></div><Badge variant="outline">{inventory.data?.length ?? 0} tracked items</Badge></div>{inventory.isLoading ? <div className="mt-6 flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading inventory</div> : inventory.data?.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-[0.12em] text-muted-foreground"><tr><th className="pb-3 font-medium">Product</th><th className="pb-3 font-medium">On hand</th><th className="pb-3 font-medium">Reserved</th><th className="pb-3 font-medium">Available</th><th className="pb-3 font-medium">Updated</th></tr></thead><tbody>{inventory.data.map(item => <tr key={item.productId} className="border-b border-border/70 last:border-0"><td className="py-4"><p className="font-medium">{item.title}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{item.sku}</p></td><td className="py-4 tabular-nums">{item.onHandQuantity}</td><td className="py-4 tabular-nums">{item.reservedQuantity}</td><td className="py-4"><Badge variant={item.onHandQuantity - item.reservedQuantity > 0 ? "default" : "secondary"}>{item.onHandQuantity - item.reservedQuantity}</Badge></td><td className="py-4 text-muted-foreground">{new Date(item.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="mt-6 rounded-xl border border-dashed border-border bg-muted/20 p-6 text-sm leading-6 text-muted-foreground">Create a catalog record to establish an inventory ledger with zero on-hand and reserved quantity.</div>}</section>
  </OperationsPage>;
}

